from pathlib import Path
import json,csv,re
root=Path.cwd();out=root/'audits/book-review-20260927/risk-social';out.mkdir(exist_ok=True)
m={x['id']:x for x in json.load(open(root/'audits/book-review-20260927/source-manifest.json'))}
alias={'habit':'BE-aa6fa610cea6','games':'BE-454e270788ba','finance':'BE-83153778433c','bubbles':'BE-df209c6ff27e','risk':'BE-ca377271f9ab','prospect':'BE-30ea0725c341','time':'BE-1b4df32f5edd','experience':'BE-97e8c87ade0d','news':'BE-aab83a55d9de','newsexp':'BE-fc2d603b6bdc','mental':'BE-19e8f1cfeb59','social':'BE-41e15d847cf3','socialshort':'BE-59e1da9c2d29','happy':'BE-7b800936f44f','happymix':'BE-6fda423152b7','influence':'DPN-656ae8351f3b','culture':'DPN-df670f4e409b','dpngames':'DPN-456bc7c5d98d','investment':'DPN-bd25b66cbcfc'}
rows=[]
def add(src,units,topic,n,needle,status,note):
 sid=alias[src];x=m[sid];target='';excerpt=''
 if n:
  p=next((root/'chapters').glob(f'{int(n):02d}-*.qmd'));lines=p.read_text().splitlines();hits=[i for i,l in enumerate(lines) if needle in l]
  if not hits:
   print('MISSING',src,topic,n,repr(needle)); return
  i=hits[0];target=f'{p.relative_to(root)}:{i+1}';excerpt=lines[i][:300]
 rows.append(dict(source_id=sid,source=x['relative_path'],units=units,topic=topic,status=status,target=target,passage=excerpt,disposition=note))
def a(s,u,t,n,k,note='Existing passage directly develops the topic.'):add(s,u,t,n,k,'already-covered',note)
def new(s,u,t,n,k,note='Added a developed example with explicit evidence limits.'):add(s,u,t,n,k,'added',note)
def st(s,u,t,n,k,note):add(s,u,t,n,k,'strengthened',note)
def omit(s,u,t,note):add(s,u,t,0,'','omitted-with-reason',note)
# Current BE06, including hidden appendix and speaker notes.
omit('habit','1–5','Opening/admin and roadmap','Navigation and classroom setup; no standalone book claim.')
a('habit','6–7','Stale popcorn, cue dependence',21,'the-popcorn-people-kept-eating')
a('habit','8–10','Habit definition, CIAO, formation curve',21,'## How habits form')
a('habit','11','Wanting versus liking',21,'wanting-can-outlast-liking')
new('habit','12','Nigrostriatal dopamine lesion and devaluation',21,'Faure and colleagues')
a('habit','13–15','Prediction errors and uncertain rewards',21,'dopamine-anticipation-and-effort')
omit('habit','16–17','Willpower/Stroop','Cross-range foundations and behavior-design chapters own these comparisons; not another trait account in Ch21.')
a('habit','18–21','Flight duration, availability and smoking urges',21,'smoking-opportunity-and-craving')
a('habit','22–24','BRAIN and compassionate recovery',21,'observing-an-urge-with-brain')
omit('habit','25–48','Ego depletion, Fogg, COM-B, implementation and habit discontinuity','Behavior-design material routed to Chapters39–40 owner; Ch21 already links action design.')
omit('habit','49–55','Administrative examples, defensive reply and clips','Administrative material and behavior-design demonstrations; cross-range owner notified.')
a('habit','56–58;61–62','Reward learning and delayed progress supplementary material',21,'## Research Lens: delay, progress')
omit('habit','59–60;64;66–68','Design/COM-B supplements and classroom administration','Handled by behavior-design owner; no empirical study imported from a video or slide instruction.')
a('habit','63;65','Marshmallow and temptation bundling',20,'## Scarcity and trust')
omit('habit','69–72','Reference slides','Source bibliography used as leads, not copied wholesale.')
# Current BE07
omit('games','1–5','Setup/roadmap','Administrative.')
a('games','6–10;13','Faces, matching incentives, resale beliefs and Keynes',23,'#two-beauty-contests')
new('games','11','GameStop and short covering',27,'#gamestop-and-short-covering')
omit('games','12','Bitcoin prices and intrinsic-value assertion','No contemporary prices or blanket zero-fundamental-value inference imported; distinct valuation frameworks would require additional development.')
a('games','14–18','Odense meeting and focal points',23,'#finding-each-other-in-odense')
omit('games','19','1966 red-light history','Historical detail unverified; adds little to already developed convention mechanism.')
st('games','20–29','Guessing game, level-k and cognitive hierarchy',23,'#cognitive-hierarchy-best-respond-to-a-mixture','Added numerical step-2 mixture versus level-2 contrast; retained participant-pool/neural caveats. Untraceable local/FT numbers not imported.')
a('games','30–33','Market timing and resale coordination',27,'#strategic-resale-and-synchronization-risk')
a('games','34–44','Players, actions, payoffs, best response and Nash',24,'#reading-a-payoff-matrix')
omit('games','45','Optional separator','Navigation.')
a('games','46–53','Prisoner dilemma, public goods, social versus private incentives',25,'## When cooperation invites exploitation')
omit('games','54–55','Cigarette-ban profits and flying-wedge history','Unverified profit attribution and historical sports claim; do not import them as causal evidence. The payoff mechanism is retained in generic matrix analysis.')
a('games','56–70','Repeated games, TFT, reputation, Golden Balls',25,'#tit-for-tat-forgiveness-and-noise','Existing discussion distinguishes noise, weak dilemma, reputation and one-shot generosity. Price-matching legal generalizations not imported.')
omit('games','71','MrBeast clip','Entertainment illustration, not research evidence; no unique explanatory gain.')
a('games','72–74','QWERTY/path dependence',24,'#conventions-and-path-dependence','Existing caveat avoids declaring historical keyboard inefficiency proven.')
st('games','75–76','Standards, units and plugs',24,'Compatibility can also preserve','Added concrete coordination/conversion costs; no claim that inherited standard was originally inferior.')
a('games','77–81','Stag hunt and payoff/risk dominance',24,'#strategic-uncertainty-the-stag-hunt')
st('games','82–84','3DO hardware/software complementarity',24,'game console','Adapted as an explicitly generic console/customer/developer coordination example; historical brand narrative not asserted.')
a('games','85–90','Mixed motives, chicken, volunteer, battle of sexes, commitment',24,'#mixed-motives-and-compatible-claims','Existing text separates game structures instead of treating every multiple-equilibrium game as pure coordination.')
omit('games','91–95','Local game outcomes','Raw data/cohort/source not established; not reused as general empirical evidence.')
a('games','96','Risk and stag-hunt thresholds',24,'## Mathematical analysis: the stag-hunt confidence threshold')
a('games','97','Princess Bride reasoning illustration',23,'Princess Bride')
a('games','98–154','Repeated supplementary game examples','23','## When do choices fit together?','Same mechanisms recur: price-war and equilibrium Ch24, cooperation Ch25, focal conventions Ch24. This block repeats main material, not 57 independent studies.')
omit('games','155–164','Summary, history and biography','Summary already represented; submarine history not verified; Fisher/Ury and negotiation routed to negotiation owner.')
st('games','165–169','All-pay escalation, winner curse, acquisition externality',23,'#research-lens-the-50-auction-and-competitive-escalation','Added quit/bid arithmetic and conditional rival-acquisition value; separates escalation from rational strategic value.')
omit('games','170','1995 airline auction story','Unverified historical figures; numerical invented acquisition example develops the point without asserting them.')
a('games','171–172','Repeated coordination and Golden Balls',25,'Golden Balls')
omit('games','173–175','Poll instruction and blank slides','Not book material or instructions to the editor.')
# Finance/bubbles
for u,t,k in [('1–10','EMH, expectations, information sets','## What market efficiency'),('11','September2013Fed surprise','### A scheduled announcement'),('12','September11 futures','### An unfolding shock'),('13–14','Challenger event','### Challenger'),('15–18','Event studies and earnings drift','### Earnings surprises'),('19–30','Size/value/momentum/reversal and disappearing patterns','### Size, value, momentum'),('31–39','Arbitrage and information incentives','#limits-to-arbitrage-seeing-an-error-is-not-enough'),('40–47','Returns/wealth and horizons','## Investing when neither prices')]:a('finance',u,t,27,k)
new('finance','48–50','Equity premium and alternative explanations',27,'#equity-premium-puzzle','Added original puzzle, myopic-loss-aversion model and disaster-risk alternative. Historical return plots are not advice.')
a('finance','51–54','Samuelson gamble and evaluation horizons',19,'#bracket-one-decision-or-a-portfolio')
a('finance','55–58','Multiplicative IPO gamble and forecast limitations',27,'## Worked example: average returns')
omit('finance','59–62','Industry concentration, polls and forecasting quotations','Industry-concentration correlation would require separate asset-pricing development; polls/quotation collage adds no distinct mechanism.')
a('finance','63–69','Historical yield/value/size and premium charts',27,'### Size, value, momentum','Sample-specific charts are covered conceptually, not every historical table reproduced; no extrapolated guaranteed ranking.')
a('finance','70–73','Palm/3Com',27,'#the-palm3com-case')
a('finance','74–83','Laboratory/lottery bubbles',27,'#one-laboratory-market')
a('finance','84–86','Shiller valuation ratios',27,'#a-two-direction-bubble-dashboard')
a('bubbles','1–9','Fundamental value and discounting',27,'## What gives an asset fundamental value?')
a('bubbles','10–13','Bubble mechanism and narrative cycle',27,'#a-bubble-is-a-reinforcing-process-hypothesis')
a('bubbles','14–18','Tulips, Newton, dotcom, housing',27,'## Historical bubbles:')
omit('bubbles','19','Selected country2008 returns','Exact sample/time provenance not established; no extra historical return table needed.')
a('bubbles','20–25','Valuation ambiguity and laboratory benchmark',27,'### A finite-lived asset')
a('bubbles','26','304-trader call market',27,'304')
a('bubbles','27','Overlapping generations',27,'Deck et al. (2014)')
omit('bubbles','28','Archived six-period classroom curve','Cohort and stopping rule unverified; 10-payment benchmark does not become 6-period expiry.')
a('bubbles','29–30','Flat fundamental values',27,'#flat-fundamentals')
a('bubbles','31–33','Credit, experience and forecasts',27,'### Experience, liquidity')
a('bubbles','34–36','Market gender composition and context',27,'#gender-context-and-a-distinct-hormonal-intervention')
a('bubbles','37–38','Behavioral strategy classification',27,'## Classification details','Portraits are mnemonic, not sampled traders; TableVI categories are not simulation frequencies.')
omit('bubbles','39–41','Synthesis and references','Source checking/navigation.')
a('bubbles','42–44','Valuation confidence and historical crashes',27,'#a-crash-does-not-settle-the-bubble-diagnosis')
omit('bubbles','45','Flash-crash image','Intraday market-structure mechanism would need separate verified development; generic crashes already distinguished from bubbles.')
a('bubbles','46–50','Asset promises, model diagnostics, lottery asset',27,'#lottery-payoffs-and-cognitive-reflection')
omit('bubbles','51','Unattributed hypothetical price path','No provenance for observed curve; book already computes published-design benchmark.')
a('bubbles','52','Liquidity and activity',27,'### Experience, liquidity')
omit('bubbles','53','Selected1929 stock returns','Selection/sample dates insufficiently documented; no causal diagnosis from winners list.')
a('bubbles','54–55;60–61','CAPE and liquidity ratios',27,'#a-two-direction-bubble-dashboard')
a('bubbles','56–59','Palm repetition',27,'#the-palm3com-case')
# Topic PDFs
omit('risk','1–4','Setup','Administrative.')
a('risk','5–7','Expected value, roulette, St Petersburg',16,'#optional-theory-lens-the-st-petersburg-puzzle')
a('risk','8–17','Expected utility, CE, insurance',16,'### Certainty equivalents')
st('risk','18–28','Risk elicitation tasks',16,'Holt and Laury','Added actual first-study payoff comparison and risk-neutral switch; class results not generalized.')
a('risk','29–31','Insurance and lottery purchase',16,'#why-do-people-buy-insurance','Simultaneous purchase alone is not proof that EU is logically violated.')
a('risk','32–33','Allais',16,'#the-allais-pattern')
a('risk','34','Reference-point puzzle',17,'### Reference dependence')
omit('risk','35–36','Disease framing','Already assigned to Chapter12 owner; Ch17 links that developed case.')
a('risk','37–44','Ellsberg and summary',16,'#the-ellsberg-urn')
omit('prospect','1–2','Setup','Administrative.')
a('prospect','3–7','Fourfold pattern, reference and neural loss-aversion evidence',17,'#loss-aversion-influential-measurable-and-bounded')
omit('prospect','8–9','Capuchin loss aversion and evolutionary story','Animal choice contrast alone does not isolate human loss-aversion mechanism; comparative fairness already bounded in Ch25.')
a('prospect','10–12','Olympic medalists',17,'Medvec')
a('prospect','13–19','Endowment, ownership, IKEA and status quo',17,'#endowment-effects','Core mechanisms and market-experience contrast retained; primate and forecast-ownership variants omitted to avoid repetitive unverified subexamples.')
a('prospect','20–26','Model, framing and hedonic editing',17,'## The prospect-theory model')
new('prospect','27','Equal five-percentage-point changes',17,'five percentage points')
a('prospect','28–30','Fourfold gain/loss behavior',17,'#the-fourfold-pattern')
omit('prospect','31','Drug-dealer and entrepreneur earnings anecdote','Unspecified evidence/selection; not proof of a specific preference mechanism.')
omit('prospect','32–33','Summary','Covered by main chapter synthesis.')
omit('time','1–2;15;30;40','Setup/separators/summary','Navigation.')
a('time','3–8','Delay comparisons and country patience',20,'### What did the patience task identify?')
a('time','9–14','Interest and compounding',20,'#interest-compounds-discounting')
a('time','16–23','Discount functions and neural interpretations',20,'## Mathematical analysis: discounted utility')
new('time','24–26','Language and future behavior',20,'#language-and-future-oriented-behavior','Added Chen2013 with Roberts2015 cultural-dependence robustness limits, not a causal grammar prescription.')
a('time','27','Future-self avatar',20,'#age-progressed-future-self')
a('time','28–29','Anticipatory utility and dread',22,"Loewenstein's (1987)",'Anticipatory utility developed with Loewenstein1987. Berns pain experiment not separately added: distinct neural/aversive mechanism would need fuller development.')
a('time','31–34','Self-control, marshmallow and development',20,'## Scarcity and trust','Longitudinal associations do not establish trait-only causation; brain two-system literalism not imported.')
a('time','35–39','Commitment and deadlines',20,'#evidence-update-commitment','Existing retraction update retained. Hugo/brick-house anecdotes omitted without verification of mechanism.')
a('experience','1–7','Description versus sampling',18,'## Description and experience')
a('experience','8–12','Disasters and experience trap',18,'### Disasters and the experience trap')
a('experience','13–18','Sampling, recency and observed frequencies',18,'## Why the gap emerges')
omit('experience','19;22–25','Vaccine-risk graphics','Outdated health figures and overgeneralized persuasion claims not imported; Ch16 retains denominator/absolute-risk principles.')
a('experience','20–21;26–35','Learning histories, hot stove, adaptive sampling',18,'### The hot-stove effect')
a('experience','36–42','Risk simulation and visual communication',18,'## Communicating risk:')
omit('experience','43–44','Quotation and summary','No unique empirical claim.')
a('news','1–16','Stocking, asymmetric shortage/leftover costs',16,'#newsvendor-worked-example')
new('news','17–27','Wetsuit demand example',16,'#newsvendor-worked-example','Preserves190/110/90 payoffs as hypothetical; does not invent distribution needed for4186units.')
st('news','28–37','Margin and pull-to-center',16,'Schweitzer and Cachon','Added high-versus-low-margin contrast and behavioral alternatives.')
omit('news','38;41','Local result charts','No cohort/raw data for generalization.')
a('news','39–40;42','Risk attitude and overconfidence diagnosis',16,'## Research Lens: every elicitation','Lottery table labels SD as variance; not copied. Risk aversion is not a sufficient explanation for pull-to-center in both margin conditions.')
omit('news','43–44','Closing images','No independent study claim.')
a('newsexp','1–2','Pull-to-center experiment',16,'#newsvendor-worked-example')
a('newsexp','3;5;7;9–11','Lottery/bomb/price-list/staircase/ambiguity tasks',16,'## Research Lens: every elicitation','Lottery5and6tieatEV18 and table SD/variance label are not carried over. Book preserves task-identification limits.')
omit('newsexp','4;6;8;12;15;18','Cohort outcome plots','Unidentified classroom sample/raw outcomes; not treated as published evidence.')
a('newsexp','13–14;16–17','CRT/Raven scores and overconfidence elicitation',15,'#confidence-must-face-a-distribution','Calibrated distinction among estimation/placement/precision; classroom score percentages omitted.')
# Mental accounting
omit('mental','1–2;5;13;21;23–24;29–30;45;53','Setup/separators/summary','Navigation.')
a('mental','3–4','Calculator price and time tradeoff',19,'## Four operations')
a('mental','6–8','Beer reference prices and transaction utility',19,'#label-acquisition-utility','Book uses original-study beer figures; JCPenney causal sales story not verified, not imported.')
a('mental','9–12','Tennis, snowstorm and attendance sunk costs',19,'Vince prepays')
a('mental','14–20','Budget labels, lost ticket, gasoline and taxi targets',19,'#boundary-case-daily-income-targets')
st('mental','22','House money/break even',19,'Consider a hypothetical fair coin','Added explicit account arithmetic; inventedeuroexample labelledhypothetical, no percentages attributed to study.')
omit('mental','25','Card Sharks exact betting figures','Gertner1993 identified, exact values not verified from accessible full primary text; not imported.')
a('mental','26–28','Break even/disposition',19,'**disposition effect**')
new('mental','31–39','Equity premium',27,'#equity-premium-puzzle')
a('mental','40–44','Myopia, Samuelson and portfolio bracket',19,'#bracket-one-decision-or-a-portfolio')
a('mental','46–51','Hedonic editing, meter, gifts and naive diversification',19,'## Four operations')
omit('mental','52','Siemens2007 delayed-work-pay example','Insufficient bibliographic detail to verify; existing coupling/intertemporal examples develop mechanism.')
# Social preferences
for source in ['social','socialshort']:
 omit(source,'1–2;12;21','Setup and summary','Navigation; in longer deck21issectiontransition.')
 a(source,'3–8','Ultimatum/dictator and interpretation',25,'#ultimatum-game-fairness-has-strategic-force')
 a(source,'9–10','Small-scale societies',25,'Lamalera','Book distinguishes Lamalera generosity from Au/Gnau high-offer rejection; slide attribution error not imported.')
 omit(source,'11','Negotiation recommendations','Routed to negotiation owner.')
 a(source,'13–17','Distributional/reciprocity models and GARP',25,'#distributional-models-make-motives-testable','Book retains parameter constraints; increasing advantageous-inequality aversion is not increasing tolerance for inequality.')
 a(source,'18–20','Neural/comparative fairness',25,'### Cross-cultural, comparative, and neural','Existing concise contrasts retained; fMRI cannot separate all social-image motives or prove a dedicated fairness center.')
a('social','22–32','Giving/taking frames and norm elicitation',25,'### Eliciting norms')
a('social','33–35','Group boundary and similarity',25,'#group-identity-changes-the-social-boundary')
omit('social','36–50','Untraceable local subgroup/game graphics','No provenance for sample and gender inference; not generalizable quantitative evidence.')
a('social','51–54','Real versus minimal groups; punishment reward',25,'#punishment-and-anticipated-reward','Group-effects core is covered, not every additional Goette design replicated.')
new('social','55','Warm glow and tax/charity distinction',25,'#warm-glow-and-giving','Adds Harbaugh2007 mandatory/voluntary contrast with reverse-inference boundary.')
omit('social','56','Self-perpetuating altruism formula','No verified attribution or estimable interpretation; no equation imported.')
a('social','57–59','Efficiency/maximin/inequality debate',25,'### Revealed preference over allocations','Existing multiple-preference identification developed; not reproducing Engelmann/Fehr comment debate without fuller sample/contrast development.')
a('social','60–61','Day-care fine',25,'#when-a-fine-changes-the-meaning')
omit('social','62','Bargaining tactics','Negotiation owner.')
a('social','63–65','Fairness and entitlement',25,'### Fairness in markets')
# Happiness sources
omit('happy','1–8','Setup and classroom provocations','No independent evidence.')
a('happy','9–13','Happiness measurement',22,'## Measuring well-being','No direct neural happiness meter claimed.')
a('happy','14–15','Income and macro correlates',22,'#income-no-magic-number','Book updates income/happiness inference; no fixed threshold or universal growth-null statement.')
omit('happy','16–26','Work norms, inequality, trust, democracy, volunteer/TV/marriage/religion associations','Substantive regression-table inspection confirms observational controls, not causal personal prescriptions. General measurement and confounding lessons retained; individual tables omitted for coherence.')
a('happy','27','Pro-social spending',22,'Dunn')
omit('happy','28–34','Positive-psychology taxonomy and10%claim','No conversion of explained variance into a percentage of happiness caused by circumstances; selected happy people do not identify causes.')
a('happy','35–40','Relationships, recovery and goals',22,'#connection-is-part-of-the-outcome','Blanket clinical/stress prescriptions omitted; chapter develops bounded practical comparisons.')
omit('happy','41','Further resources','Reading suggestions, not evidence.')
a('happy','42','Sunk/opportunity costs',19,'#close-sunk-costs')
omit('happy','43–46','Spiritual and self-help aphorisms','Not scientific evidence or a guaranteed happiness intervention.')
omit('happymix','1–2','Title and outline','This86slidefile is mostly a finance deck despite its happiness filename.')
new('happymix','3','Lottery winners and accident victims',22,'Brickman, Coates, and Janoff-Bulman','Original smallcross-sectional1978contrast added alongside randomized-prize2020followup; rejects claim of equal happiness.')
a('happymix','4','Tenure forecast illustration',22,'#impact-bias-and-focalism','Slide misattributes tenure claim to Brickman1978; no wrong reference imported.')
a('happymix','5–86','Finance material in misnamed happiness file',27,'## What market efficiency','Read text/notes; topics recur in current BE08 and DPN investment, mapped in detailed rows above.')
# DPN social influence, culture and games/investment
omit('influence','1–2;12–15;37;42;62','Setup/transitions/summary','Navigation.')
a('influence','3–11','Chimpanzee matching, social learning, overimitation and mimicry',26,'#the-social-brain-is-not-simply-the-individually-smartest-brain')
omit('influence','16–36','Attribution, self-serving explanations and expectations','Cross-range chapters7/9/10/29 leads sent to root; do not duplicate explanations here.')
a('influence','38–41','Asch and conformity',26,'#conformity-is-an-outcome-not-a-mechanism')
omit('influence','43','Shopping-cart origin anecdote','Unverified historical particulars; social learning mechanism already established experimentally.')
a('influence','44–46','MusicLab',26,'Salganik')
new('influence','47','Facebook emotional-content experiment',26,'#social-feed-and-expression')
a('influence','48','Cooperation networks',25,'Fowler')
new('influence','49','Cross-norm disorder',26,'#cross-norm-disorder')
a('influence','50–51','Energy norms and boomerang',26,'Schultz')
new('influence','52–53','Smoke-room bystanders',28,'The **smoke-filled room**','Adds exact experiment distinct from existing intercom study, preserves individual/group denominators.')
a('influence','54–60','Pluralistic ignorance/norm cases',26,'**pluralistic ignorance**')
omit('influence','61','Anti-drug campaign','Slide conflates campaign names; observational exposure and unintended effects need accurate program-specific evidence. No claim imported.')
omit('culture','1–5','National anecdotes and COVID comparison','No stereotype treated as a diagnosis or current health-policy claim.')
a('culture','6','Multicultural creativity',29,'Maddux')
omit('culture','7–8;28–30;39–49;52–54;57;71–74','Aviation, language priming and cross-cultural negotiation','Sent to foundations/negotiation owner; English-only aviation narrative not imported.')
omit('culture','9;27;33;50–51;55–56;59–60;67','Separators/admin','Navigation.')
a('culture','10–17','Personality, cultural cognition, scene and triad',29,'#a-three-object-prediction')
new('culture','18–19','Dialectical contradiction',29,'Peng and Nisbett (1999)')
new('culture','20–21','Starbucks chair behavior',29,'Talhelm, Zhang, and Oishi (2018)')
a('culture','22–26','Rice/wheat and honor',29,'#how-livelihoods-can-shape-cultural-learning')
new('culture','31–32','Future grammar and saving',20,'#language-and-future-oriented-behavior')
a('culture','34–38;61–66','Country dimensions and variation',29,'#cultural-dimensions-do-not-diagnose-a-person','Representative dimensions developed; do not add a trait scorecard that diagnoses individuals from nationality.')
omit('culture','58;68–70;75–76','Alibaba names, old happiness rankings, MPs gender statistic, success/failure and climate','Historical/statistical details unverified or too stereotyped; no deterministic national prescriptions.')
omit('dpngames','1–3;5–8;10;12;14;18–19;22–23;26;31;37;39;42;51;54;57;61–63','Admin, local charts, history and entertainment','Compared with current BE07. Repeated unrelated nudge speaker notes recognized as stale, not author instructions. Cigarette profit/history not imported.')
a('dpngames','4;9;11;13;15–17;20–21;24–25','Beauty, focal meeting and hierarchy',23,'#cognitive-hierarchy-best-respond-to-a-mixture')
a('dpngames','27–30;32–36;38;40–41','Matrices, Nash, PD and institutional conflict',24,'#reading-a-payoff-matrix')
a('dpngames','43–50;52–53','Reciprocity, reputation and Golden Balls',25,'#tit-for-tat-forgiveness-and-noise')
a('dpngames','55–56;58–60','Ultimatum bargaining and interpretation',25,'#ultimatum-game-fairness-has-strategic-force','Absolute high-stakes invariance claim not retained.')
a('investment','1–22','Valuation, EMH, Fed/Challenger and event study',27,'## What market efficiency','Current BE08 notes correct older error: event studies examine returns, not earnings effects; minute graph does not show millisecond response.')
a('investment','23–38','Trading patterns and arbitrage',27,'### Size, value, momentum','No-guarantee framing and joint hypotheses retained. Exact triangular-arbitrage arithmetic not necessary after existing no-risk vs costly-correction contrast.')
new('investment','39–48','Equity premium',27,'#equity-premium-puzzle')
a('investment','49–56','Myopic evaluation, multiplicative wealth and disposition',19,'#bracket-one-decision-or-a-portfolio')
omit('investment','57–60','Concentration paper, polls, quotations','As BE08: extra asset-pricing hypothesis omitted, no unsupported investment recommendation.')
a('investment','61–67','Historical return tables',27,'### Size, value, momentum')
a('investment','68–71','Palm3Com',27,'#the-palm3com-case')
a('investment','72–81','Experimental and lottery bubbles',27,'#lottery-payoffs-and-cognitive-reflection','Original slide75 dividend formula has .048 typo; existing book specifies coherent probabilities and mean, does not copy typo.')
a('investment','82–84','Shiller and historical ratios',27,'#a-two-direction-bubble-dashboard')
# Final source-coordinate check against actual current slide headers.
rows[:]=[r for r in rows if r['source_id']!=alias['finance']]
a('finance','1–10','EMH, expectations and information sets',27,'## What market efficiency')
a('finance','11–14;50–52','Fed,September11andChallenger',27,'### A scheduled announcement')
a('finance','15–18','Event study and earnings drift',27,'### Earnings surprises')
a('finance','19–28;30;43–46;74–79','Size/value/momentum/reversal tables and polls',27,'### Size, value, momentum','Specific historical tables illustrate patterns; no universal prediction or current portfolio advice. Legacy slide24 unverified numerical bars omitted.')
a('finance','29;31–33','Publication decay and information incentives',27,'McLean and Pontiff')
omit('finance','34–36;69','References and archived login/payment rules','Not book prose or executable instructions.')
a('finance','37–38','Fish market and irreversible fuel cost',23,'## Applied module: market rules')
a('finance','39–41','Current class asset market rules',27,'### A finite-lived asset','Published benchmark is kept separate from classroom12-period design and current settlement rules.')
a('finance','42;55–57;72–73','Forecast discipline',27,'#a-falsifiable-investment-memo')
a('finance','47–48;59;66–67','Random charts and moving-average timing',27,'**Technical analysis**','No unsupported broker failure percentage or25%volatility reduction from unreplicated chart.')
a('finance','49','IBM versus StandardOil',27,'Comparing IBM','Avoids mixing operating-growth and return windows; selected companies are not causal evidence.')
omit('finance','53','Legacy gold response chart','Original timestamp/data not verified; documented Fed S&P example supplies event lesson.')
a('finance','54','2024election-night market response',27,'#election-night-the-announcement')
a('finance','58;60–62','CAPM/factors/alpha/strict arbitrage',27,'**capital asset pricing model**')
a('finance','63','Multiplicative wealth example',27,'## Worked example: average returns')
a('finance','64','CUBA fund',27,'**CUBA fund**')
omit('finance','65','Financial intermediation unit cost','Distinct productivity question, not EMH test. No need to add industry-cost chapter; erroneous GDP denominator not imported.')
omit('finance','68','Buffett net-worth graphic','Third-party selected-success estimates not audited; transparent compounding already present.')
a('finance','70','Triangular arbitrage',27,'#limits-to-arbitrage','Strict arbitrage versus risky convergence distinction covered; extra arithmetic cycle omitted for chapter coherence.')
a('finance','71','Disposition exercise',19,'**disposition effect**')
new('finance','80','Long-horizon realized equity premium',27,'#equity-premium-puzzle','New puzzle discussion also draws on detailed mental-accounting and older investment slides, not misidentified current48–50.')
a('finance','81–84','Palm3Com',27,'#the-palm3com-case')
a('finance','85–86','Shiller ratios',27,'#a-two-direction-bubble-dashboard')
for r in rows:
 if r['source_id']==alias['games'] and r['units']=='72–74':r['units']='72–75'
 if r['source_id']==alias['games'] and r['units']=='75–76':r['units']='76–77'
 if r['source_id']==alias['games'] and r['units']=='77–81':r['units']='78–81'
 if r['source_id']==alias['mental'] and r['units']=='1–2;5;13;21;23–24;29–30;45;53':r['units']='1–2;5;13;21;29–30;45;53'
 if r['source_id']==alias['mental'] and r['units']=='22':r['units']='22–24'
with (out/'coverage.csv').open('w') as f:
 w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
(out/'coverage.json').write_text(json.dumps(rows,indent=2,ensure_ascii=False)+'\n')
print(len(rows),'verified-location rows across',len(set(r['source_id'] for r in rows)),'source files')
