<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Visible choices are only the endpoint. This book follows decisions in the making—from attention, interpretation, prediction, and valuation to influence, communication, negotiation, and the design of environments that make better judgment and action possible.">

<title>23&nbsp; Strategic Interdependence – Decision in the Making</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/24-behavioral-game-theory-equilibrium-is-a-benchmark-not-a-portrait.html" rel="next">
<link href="../parts/part-4.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d2ab3828f0446ed9f3a10bc4efc982a8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-4.html">Part IV. Strategic and Social Decisions</a></li><li class="breadcrumb-item"><a href="../chapters/23-strategic-interdependence-the-best-move-depends-on-other-minds.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Strategic Interdependence</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Decision in the Making</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/warrenchang/decisionbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-to-use-this-book.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to Use This Book</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-to-read-evidence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to Read the Evidence in This Book</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part I. How a Choice Takes Shape</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-how-decisions-should-be-made-and-how-they-actually-are.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Normative, Descriptive, and Prescriptive</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-building-a-better-decision-alternatives-opportunity-cost-information-and-robustness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Building a Better Decision</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-attention-what-becomes-evidence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Limited Attention</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-the-predictive-mind-perception-is-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Predictive Mind</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-expectations-when-predictions-become-causes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Expectations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-valuation-how-options-become-worth-choosing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Valuation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-the-narrator-after-choice-why-reasons-are-not-always-causes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Narrator After Choice</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part II. Judgment Under Uncertainty</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-fast-and-frugal-thinking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Intuition and Deliberation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-what-feels-likely-availability-affect-and-resemblance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Availability, Affect, and Representativeness</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-beliefs-that-defend-themselves.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Confirmation Bias and Motivated Reasoning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-when-context-rewrites-comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Anchors, Halos, and Decoys</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-framing-when-the-same-facts-become-different-decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Framing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-accessibility-familiarity-and-ease.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Priming, Fluency, and Familiarity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-base-rates-conditional-probability-and-bayesian-updating.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Base Rates and Updating</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-samples-randomness-regression-and-calibration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Randomness and Overconfidence</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part III. Risk, Time, and Well-Being</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-risky-decision-making-a-probability-is-not-yet-a-feeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Risky Decision Making</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17-prospect-theory-gains-and-losses-begin-at-a-reference-point.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Prospect Theory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/18-decisions-from-experience-when-rare-events-are-not-encountered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Decisions From Experience</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/20-mental-accounting-money-is-fungible-minds-label-it.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Mental Accounting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/19-intertemporal-decision-making-why-later-loses-to-now.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Intertemporal Decision Making</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/21-habits-wanting-and-self-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Habits, Wanting, and Self-Control</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/22-deciding-for-a-better-life-satisfaction-connection-and-meaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Deciding for a Better Life</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part IV. Strategic and Social Decisions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/23-strategic-interdependence-the-best-move-depends-on-other-minds.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Strategic Interdependence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/24-behavioral-game-theory-equilibrium-is-a-benchmark-not-a-portrait.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Coordination and Focal Points</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/25-cooperation-and-social-preferences-self-interest-is-not-the-only-payoff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Cooperation and Social Preferences</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/26-social-norms-and-conformity-when-other-people-become-evidence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Social Norms and Conformity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/27-markets-mispricing-and-bubbles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Markets, Mispricing, and Bubbles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/28-authority-groupthink-and-shared-responsibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Authority, Groupthink, and Shared Responsibility</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/29-culture-and-identity-the-same-action-is-not-the-same-act.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Culture and Identity</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part V. Persuasion, Communication, and Connection</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/30-persuasion-changing-minds-means-updating-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Persuasion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/31-why-stories-move-minds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Why Stories Move Minds</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/32-building-an-evidence-aligned-message.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Building an Evidence-Aligned Message</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/33-communication-language-is-not-a-file-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Communication</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/34-connection-and-repair-warm-honesty-makes-truth-usable.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Connection and Repair</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part VI. Negotiating Joint Decisions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/35-negotiation-as-joint-decision-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Negotiation as Joint Decision Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/36-preparing-and-claiming-value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Distributive Negotiation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/37-creating-value-across-differences.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Integrative Negotiation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/38-designing-better-agreements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Designing Better Agreements</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part VII. Designing Better Decisions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/39-behavior-design-make-the-better-action-easier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Behavior Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/40-choice-architecture-the-environment-gets-a-vote.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Choice Architecture</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/41-decision-hygiene-build-a-process-that-can-learn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Decision Hygiene</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/42-data-driven-decision-making.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Deciding With Data and AI</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/appendix-a-rational-choice-and-decision-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Rational Choice and Decision Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/appendix-b-evolutionary-explanations-of-value-choice-and-rationality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Evolutionary Explanations of Value, Choice, and Rationality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/appendix-literature-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Conducting and Writing a Literature Review</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/appendix-e-how-behavioral-evidence-is-built.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Running an Experimental Study: From Question to Credible Evidence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/appendix-f-when-evidence-breaks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">When Evidence Breaks: The Replication Crisis and Research Integrity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/appendix-c-portable-course-tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Portable Tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/appendix-d-index-of-major-course-examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Index of Major Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../concept-index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Index of Concepts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About This Book</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-goals" id="toc-learning-goals" class="nav-link active" data-scroll-target="#learning-goals">Learning goals</a></li>
  <li><a href="#finding-each-other-in-odense" id="toc-finding-each-other-in-odense" class="nav-link" data-scroll-target="#finding-each-other-in-odense">Coordinating through shared expectations</a></li>
  <li><a href="#two-beauty-contests" id="toc-two-beauty-contests" class="nav-link" data-scroll-target="#two-beauty-contests">Separating preference from prediction</a></li>
  <li><a href="#opening-puzzle-should-a-sophisticated-player-choose-zero" id="toc-opening-puzzle-should-a-sophisticated-player-choose-zero" class="nav-link" data-scroll-target="#opening-puzzle-should-a-sophisticated-player-choose-zero">Anticipating how far others reason</a>
  <ul class="collapse">
  <li><a href="#limited-strategic-depth-level-k" id="toc-limited-strategic-depth-level-k" class="nav-link" data-scroll-target="#limited-strategic-depth-level-k">Reasoning and learning about other players</a></li>
  </ul></li>
  <li><a href="#equilibrium-when-choices-fit-together" id="toc-equilibrium-when-choices-fit-together" class="nav-link" data-scroll-target="#equilibrium-when-choices-fit-together">When do choices fit together?</a></li>
  <li><a href="#application-anticipate-the-response-before-committing" id="toc-application-anticipate-the-response-before-committing" class="nav-link" data-scroll-target="#application-anticipate-the-response-before-committing">Anticipate the response before committing</a></li>
  <li><a href="#practice-lab" id="toc-practice-lab" class="nav-link" data-scroll-target="#practice-lab">Practice Lab</a></li>
  <li><a href="#take-it-forward" id="toc-take-it-forward" class="nav-link" data-scroll-target="#take-it-forward">Take it forward</a></li>
  <li><a href="#references-cited-in-this-chapter" id="toc-references-cited-in-this-chapter" class="nav-link" data-scroll-target="#references-cited-in-this-chapter">References cited in this chapter</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/warrenchang/decisionbook/edit/main/chapters/23-strategic-interdependence-the-best-move-depends-on-other-minds.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/warrenchang/decisionbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/warrenchang/decisionbook/blob/main/chapters/23-strategic-interdependence-the-best-move-depends-on-other-minds.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-4.html">Part IV. Strategic and Social Decisions</a></li><li class="breadcrumb-item"><a href="../chapters/23-strategic-interdependence-the-best-move-depends-on-other-minds.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Strategic Interdependence</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Strategic Interdependence</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>The Best Move Depends on Other Minds</em></p>
<div id="chapter-23-start" class="chapter-epigraph">
<blockquote class="blockquote">
<p>“Now, here, you see, it takes all the running you can do, to keep in the same place.”</p>
<p>— Lewis Carroll, <a href="https://www.gutenberg.org/cache/epub/12/pg12-images.html"><em>Through the Looking-Glass</em></a>, 1871, ch.&nbsp;II</p>
</blockquote>
</div>
<p><span id="opening-puzzle-meet-me-in-odense"></span>You start chatting with someone in the queue at a concert and find that the two of you really click. You decide to watch the performance together. Once inside, you lose each other in the crowd before you have exchanged phone numbers.</p>
<p>You could head toward the stage, return to the entrance, or wait where you last saw them. A good spot near the stage would let you enjoy the music, but it will not help you find each other if they have gone back to the entrance.</p>
<p>The other person faces the same problem. Where you should go depends on where you expect them to go—and on where they expect to find you.</p>
<div class="core-idea callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Core Idea
</div>
</div>
<div class="callout-body-container callout-body">
<p>In a strategic interaction, your outcome depends on your action and on other people’s actions. They are choosing too, often while trying to anticipate you. Understanding that dependence means looking beyond what you prefer to what others have reason to do.</p>
</div>
</div>
<section id="learning-goals" class="level2">
<h2 data-anchor-id="learning-goals">Learning goals</h2>
<ul>
<li>Explain strategic interdependence through three situations in which the outcome depends on other people’s choices.</li>
<li>Distinguish personal preferences from expectations about others, including what they expect you to do.</li>
<li>Use equilibrium to describe choices that fit together, while recognizing why it may not predict actual play.</li>
</ul>
</section>
<section id="finding-each-other-in-odense" class="level2">
<h2 data-anchor-id="finding-each-other-in-odense">Coordinating through shared expectations</h2>
<p>Returning to the main entrance might seem promising because you both came through it. You know the other person has seen it, and they know you have too. That shared experience gives you a reason to expect the same destination, even though you know little about each other’s habits or preferences.</p>
<p>But the stage may seem more obvious to them: that is where you intended to watch the performance together. A place can make sense to each of you for different reasons without bringing you together. Waiting matters as well. If one person arrives just after the other leaves to search elsewhere, choosing the same destination will still fail.</p>
<p>The other person is also trying to work out what you will do. They might return to the entrance because they expect you to see it as an obvious place to wait. Your uncertainty concerns someone who is responding to their own uncertainty about you. The next chapter examines how a shared experience, a landmark, or a convention can help people settle on the same answer.</p>
<p>Game theory calls the value of an outcome to a player a <strong>payoff</strong>. Here, the value of choosing a place depends partly on whether the other person goes there too. The next exercise separates personal preference from this dependence on another person’s choice more sharply.</p>
</section>
<section id="two-beauty-contests" class="level2">
<h2 data-anchor-id="two-beauty-contests">Separating preference from prediction</h2>
<p>Imagine a classroom exercise in which everyone receives the same set of labeled portraits. First, each participant selects the face they personally find most attractive. There is no correct answer and no reward for matching anyone else.</p>
<p>Now the instructor changes the rule. Participants are paired, and both receive a reward if they select the same face. Different selections earn nothing. Each chooses again without seeing the partner’s answer. How would this rule change what you consider when choosing?</p>
<p>Nothing about the faces has changed, but a different feature of them now matters: which one the other participant is likely to select. You might keep your original choice because you expect them to share your preference. You might instead choose a face you like less because it seems more widely appealing or distinctive. Either decision can be sensible under the new rule.</p>
<p>If matching earns 15 units, a face’s expected reward depends on how likely the partner is to select it. For a player concerned only with that reward, the best response is to choose a face with the highest chance of a match. Your own ranking supplies possible evidence about their choice, but it no longer directly determines the monetary payoff.</p>
<p>The two tasks separate <strong>what I prefer</strong> from <strong>what I expect someone else to choose</strong>. A change of answer need not mean your taste changed or that you gave in to social pressure. The incentive changed.</p>
<div id="math-matching-reward">
<div class="research-lens mathematical-analysis callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Mathematical analysis: the expected reward from matching
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If your reward is 15 units, its expected value from selecting face <span class="math inline">\(j\)</span> is</p>
<p><span class="math display">\[
15\times\Pr(\text{the other person selects face }j).
\]</span></p>
<p>Because every successful match pays the same amount, maximizing the expected reward means maximizing the chance of a match.</p>
</div>
</div>
</div>
</div>
<p><span id="the-other-person-is-predicting-too"></span></p>
<p>The second participant is also paid to match. They may choose what they think <em>you</em> expect them to select. This makes a face that is commonly recognized as striking potentially useful even when neither person ranks it first privately. Shared expectations can converge on a choice that would not win a private-preference poll.</p>
<p>Keynes (1936, Chapter 12) used a newspaper beauty contest to illustrate a related difficulty in investing: anticipating others’ judgments can matter alongside judging an asset’s underlying value. His contest had different rules from this pair-matching exercise, but the distinction transfers. A trader expecting to resell soon must consider what the next buyer will pay, as <a href="../chapters/27-markets-mispricing-and-bubbles.html#chapter-27-start">Markets, Mispricing, and Bubbles</a> examines. That concern can influence trading without proving that every price movement reflects imitation or that fundamentals have ceased to matter.</p>
<p>To investigate a change of answer in the face task, record both the person’s private ranking and their prediction of the other participant’s selection. Observing the final choice alone cannot tell us whether they anticipated shared tastes, a salient face, or a convention learned from an earlier round.</p>
</section>
<section id="opening-puzzle-should-a-sophisticated-player-choose-zero" class="level2">
<h2 data-anchor-id="opening-puzzle-should-a-sophisticated-player-choose-zero">Anticipating how far others reason</h2>
<p>In a group of at least three people, everyone chooses a real number from 0 to 100. The person closest to two-thirds of the group’s mean wins a fixed prize, shared equally in a tie. Choose your number before continuing.</p>
<p>The face task rewarded matching another person’s answer. Here the target itself depends on everyone’s answers, including yours. If the mean were 45, the target would be 30; if it were 30, the target would be 20. A number becomes a good choice through its relation to what the group chooses.</p>
<p>One starting guess is that people will choose roughly at random across the range, giving an expected mean of 50. Two-thirds of that is about 33. But the other players can see the same rule. If you expect them to take that step, a number around 22 becomes attractive. If you expect them to anticipate that step too, you may aim near 15.</p>
<p>These numbers approximate where a player might aim. Your own number influences the mean, and winning depends on how close the other numbers are to the target. Reasoning from an expected average becomes more useful in a large group, where your own effect on that average is small.</p>
<section id="limited-strategic-depth-level-k" class="level3">
<h3 data-anchor-id="limited-strategic-depth-level-k">Reasoning and learning about other players</h3>
<p>Suppose most of the others stop around 33. A choice near 22 may beat them, while taking several more steps toward zero could leave you far from the target. Understanding the rule is useful, but winning also requires judging how the other people will use it.</p>
<p>Nagel’s (1995) guessing-game experiments found behavior consistent with limited steps of reasoning, rather than everyone following the argument all the way down to zero. <strong>Level-<em>k</em></strong> models describe such steps (Nagel, 1995; Stahl &amp; Wilson, 1995). Level 0 supplies a starting rule, such as random choice; level 1 responds to that rule; level 2 responds to level 1. The familiar 50-to-33-to-22 sequence illustrates the idea.</p>
<p>The starting assumption matters as much as the number of steps. A sophisticated player may choose a relatively high number because they expect others to reason little.</p>
<p>The <a href="https://youtu.be/0sPVEBAtwmg">poisoned-goblet scene from <em>The Princess Bride</em></a> makes this vulnerability memorable: each additional “I think that you think” rests on assumptions about the opponent. More reasoning cannot rescue a mistaken premise merely by extending it.</p>
<p><span id="the-action-does-not-identify-the-thought"></span></p>
<p>A choice of 22 could reflect two steps from a random anchor. It could also come from remembering a previous classroom game, predicting a mean of 33 for another reason, or copying a familiar answer. Behavioral game theory compares such explanations rather than assigning a reasoning type from one number (Camerer, 2003; Crawford et al., 2013).</p>
<p>A further possibility is that players expect different people to reason differently. <strong>Cognitive hierarchy</strong> models allow a mixture of reasoning depths rather than assuming everyone is exactly one level below the player (Camerer et al., 2004). The Research Lens at the end of the chapter develops this model and the evidence across participant groups.</p>
<p><span id="learning-is-not-the-same-as-deeper-initial-reasoning"></span></p>
<p>After several rounds, guessing-game choices often move downward. A player who saw a low group mean may revise their expectation; another may repeat a number that nearly won. Someone else may finally understand the rule. These routes can produce similar movement while implying different lessons about the next group.</p>
<p><strong>Belief learning</strong> updates expectations about others. <strong>Reinforcement learning</strong> increases the tendency to repeat an action after a favorable outcome. <strong>Imitation</strong> copies another player’s action. To distinguish them, vary the feedback: show the distribution of choices, show only the player’s own earnings, or show which action won. Record expectations before each round as well as choices afterward.</p>
<p>A useful account should explain why the specified feedback changes behavior. Simply describing a falling mean as “greater rationality” leaves that explanation unfinished. Change in the prevalence of strategies across a population is a further question, developed in <a href="../chapters/25-cooperation-and-social-preferences-self-interest-is-not-the-only-payoff.html#advanced-research-track-evolutionary-and-spatial-models">Chapter 25’s research lens</a>.</p>
</section>
</section>
<section id="equilibrium-when-choices-fit-together" class="level2">
<h2 data-anchor-id="equilibrium-when-choices-fit-together">When do choices fit together?</h2>
<p>The three situations have raised the same difficulty in different forms: you are deciding while other people are deciding too. Is there a combination of choices at which nobody would gain by changing their own choice alone?</p>
<p>A <strong>Nash equilibrium</strong> is such a combination: each player’s strategy is a best response to the others (Nash, 1950). A <strong>best response</strong> gives the highest payoff against the other players’ specified strategies. Equilibrium describes how the choices fit together; it does not require that the players reached them through a particular thought process.</p>
<p>In the meeting problem, suppose both people choose an accessible place and time where they can meet. Switching elsewhere alone would defeat their purpose. Many meeting arrangements could have this property, so identifying an equilibrium does not yet explain which one you and your new acquaintance will select. Likewise, several matching faces could satisfy the reward rule in the second exercise.</p>
<p>The guessing game has a different endpoint. Under its specified rules, the unique Nash equilibrium is for everyone to choose zero (Nagel, 1995). If everyone else chooses zero, choosing zero shares the prize. Choosing a positive number raises the mean, but in a group of at least three it leaves the zero-choosers closer to the resulting target, so the deviation loses.</p>
<p>The ladder in <a href="#fig-level-k-reasoning-ladder" class="quarto-xref">Figure&nbsp;<span>23.1</span></a> connects a few steps of reasoning with that endpoint. It separates where the argument can lead from where a particular group is likely to stop.</p>
<div id="fig-level-k-reasoning-ladder" class="quarto-float quarto-figure quarto-figure-center" alt="An illustrative ladder starts from an expected random-choice anchor of fifty, then gives approximately thirty-three, twenty-two, fifteen, and the equilibrium zero for a two-thirds-of-the-mean guessing game.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-level-k-reasoning-ladder-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/level-k-reasoning-ladder.svg" class="img-fluid figure-img" style="width:100.0%" alt="An illustrative ladder starts from an expected random-choice anchor of fifty, then gives approximately thirty-three, twenty-two, fifteen, and the equilibrium zero for a two-thirds-of-the-mean guessing game.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-level-k-reasoning-ladder-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;23.1: An illustrative level-<em>k</em> ladder for the two-thirds guessing game starts from a random-choice anchor with mean 50, then aims near 33, 22, and 15. These are large-group approximations; the game’s equilibrium is 0.
</figcaption>
</figure>
</div>
<p>Choosing zero by yourself does not put the group in equilibrium. If others choose positive numbers, zero can lose. Your decision still depends on what you have reason to expect from these players. <a href="../chapters/24-behavioral-game-theory-equilibrium-is-a-benchmark-not-a-portrait.html#chapter-24-start">Coordination and Focal Points</a> introduces payoff matrices and develops equilibrium analysis from this starting point.</p>
</section>
<section id="application-anticipate-the-response-before-committing" class="level2">
<h2 data-anchor-id="application-anticipate-the-response-before-committing">Anticipate the response before committing</h2>
<p>A manager may propose a new reporting system because it improves their team’s work. Other departments may delay adoption because the system is useful only if everyone joins, because they bear more of the transition cost, or because they prefer to keep information private.</p>
<p>Start by identifying what each person can do and how combinations of actions affect their payoffs. Separate your own preference from your prediction of theirs. Then ask what they know about your plan and what response they expect if they hesitate. A useful prediction identifies what could change another person’s choice.</p>
<p><span id="ethics-whose-payoff-enters-the-model"></span></p>
<p>Include the people affected by the arrangement, even if they cannot choose within it. An agreement between competitors can harm customers; a shared convention can exclude newcomers. A successful strategy for the people at the table may impose costs on others whose interests the model leaves out.</p>
<p>For an exercise in model construction, watch the <a href="https://youtu.be/Q-a1I61sIO8">strategic-interdependence scene from <em>A Beautiful Mind</em></a>. List the participants’ options, including those of the people the characters discuss, and check whether anyone could gain by departing from the proposed arrangement.</p>
</section>
<section id="practice-lab" class="level2">
<h2 data-anchor-id="practice-lab">Practice Lab</h2>
<p>Revisit the three examples in order. For the meeting problem, pair people who know little about one another and ask them to imagine being separated at a crowded event. Have each choose a place to wait independently, then compare the cues each expected the other to recognize. For the face task, give everyone the same set of labeled portraits, then compare private rankings with rewarded matching choices. For the guessing game, record an initial choice and prediction of the mean, then play five rounds with feedback.</p>
<p>Before revealing each result, ask participants what they expect others to do and why. Afterward, identify one change in behavior and develop two possible explanations. Propose a change in information or incentives that would make those explanations predict different choices. Knowing an equilibrium answer is less informative than being able to explain when it would help predict the people actually playing.</p>
</section>
<section id="take-it-forward" class="level2">
<h2 data-anchor-id="take-it-forward">Take it forward</h2>
<p>The meeting problem required anticipating where your new acquaintance would go to look for you. The face task separated private taste from rewarded prediction, and the guessing game made you examine where other people’s reasoning might stop. In each case, evaluating your own choice required a view of someone else’s action.</p>
<p>Before committing to a plan, identify the response you are counting on and what gives you reason to expect it. The next chapter makes that dependence visible in payoff matrices, then asks why people can struggle to coordinate even when they understand what would work.</p>
<p><span id="cognitive-hierarchy-best-respond-to-a-mixture"></span></p>
<div class="research-lens callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Research Lens: cognitive hierarchy and the evidence
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In cognitive hierarchy, a step-<span class="math inline">\(k\)</span> thinker best responds to a distribution of steps <span class="math inline">\(0\)</span> through <span class="math inline">\(k-1\)</span>. Camerer, Ho, and Chong (2004) model the population frequency of step <span class="math inline">\(h\)</span> with a Poisson distribution,</p>
<p><span class="math display">\[
f(h)=\frac{e^{-\tau}\tau^h}{h!},
\]</span></p>
<p>and renormalize the distribution over the lower steps the player believes exist. The parameter <span class="math inline">\(\tau\)</span> controls the average number of steps. The authors report that a value around 1.5 fits behavior across many games, although fitted values differ by task and participant pool.</p>
<p><a href="#tbl-beauty-contest-groups" class="quarto-xref">Table&nbsp;<span>23.1</span></a> reproduces selected guessing-game results from their Table II. The fitted <span class="math inline">\(\tau\)</span> values in this table were chosen to match the observed mean.</p>
<div id="tbl-beauty-contest-groups" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-beauty-contest-groups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;23.1: Descriptive guessing-game results and fitted reasoning depths (Camerer et al., 2004, Table II)
</figcaption>
<div aria-describedby="tbl-beauty-contest-groups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Participant pool</th>
<th style="text-align: right;">Sample size</th>
<th style="text-align: right;">Mean choice</th>
<th style="text-align: right;">Modal choice</th>
<th style="text-align: right;">Fitted <span class="math inline">\(\tau\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Chief executives</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">37.9</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="even">
<td>German students</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">37.2</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">1.1</td>
</tr>
<tr class="odd">
<td>U.S. high-school students</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">32.5</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">1.6</td>
</tr>
<tr class="even">
<td>Economics PhDs</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">27.4</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">2.3</td>
</tr>
<tr class="odd">
<td>Portfolio managers</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">24.3</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">2.8</td>
</tr>
<tr class="even">
<td>Caltech students</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">23.0</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td>Newspaper participants</td>
<td style="text-align: right;">7,884</td>
<td style="text-align: right;">23.0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td>Game theorists</td>
<td style="text-align: right;">136</td>
<td style="text-align: right;">19.1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3.7</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The mean was 37.9 among the chief executives and 19.1 among the game theorists, but these are comparisons across settings and selected participant pools. Substantial variation remains within pools, and alternative beliefs can produce the same number. Model evaluation should compare predictions against new choices or against experimental changes on which rival explanations disagree.</p>
<p>The zero endpoint in the guessing game can also be approached through iterated elimination of weakly dominated high choices. The target cannot exceed <span class="math inline">\(66\frac{2}{3}\)</span>; after excluding choices above that bound, the next upper bound is <span class="math inline">\(44\frac{4}{9}\)</span>, then <span class="math inline">\(29\frac{17}{27}\)</span>, and so on toward zero (Nagel, 1995). A weakly dominated choice never yields more than an alternative against the others’ possible choices and yields less in at least some cases. This is a stronger assumption about what players rule out than simply saying that they want to win. <a href="../chapters/24-behavioral-game-theory-equilibrium-is-a-benchmark-not-a-portrait.html#chapter-24-start">Chapter 24</a> develops the comparison of strategies.</p>
<p>Coricelli and Nagel (2009) compared play against human and computer opponents using behavioral and neural measures. Their findings associate strategic reasoning with differences in processing when the opponent changes. Such evidence can help discriminate between accounts.</p>
</div>
</div>
</div>
<p><span id="research-lens-the-50-auction-and-competitive-escalation"></span></p>
<div class="research-lens callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Research Lens: the €50 auction and competitive escalation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In Shubik’s dollar-auction game, the highest bidder wins the prize, but the second-highest bidder must also pay their final bid (Shubik, 1971). Early entry looks attractive. Once two people are competing, another small bid can appear cheaper than accepting a certain loss. Each expects that the next bid may make the rival quit. If both reason this way, bids can exceed the prize.</p>
<p>The game makes it possible to examine <strong>competition neglect</strong>, when bidders enter without accounting for rivals’ persistence, and <strong>escalation of commitment</strong>, when earlier choices make stopping difficult (Staw, 1976). A further bid can also be a forward-looking response to a belief that the rival will stop.</p>
<p>Competitive acquisition creates a related trap. When bidders have noisy estimates of a common value, winning can be bad news: the winner may simply be the most optimistic bidder (Bazerman &amp; Samuelson, 1983). This winner’s-curse problem concerns what winning reveals about the estimate, whereas the dollar auction concerns a rule requiring the runner-up to pay. Before entering, examine the rules and likely competitors, separate private synergies from common value, and set a reservation price based on future benefits and costs.</p>
</div>
</div>
</div>
<div class="applied-module callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Applied module: market rules change the strategic game
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Buyers and sellers can stand to gain from trade yet fail to find acceptable terms. Compare <a href="#tbl-market-institutions" class="quarto-xref">Table&nbsp;<span>23.2</span></a>: each rule changes who can act, what they observe, and how a price forms.</p>
<div id="tbl-market-institutions" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-market-institutions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;23.2: Market institutions alter information, timing, and bargaining power
</figcaption>
<div aria-describedby="tbl-market-institutions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Institution</th>
<th>Basic rule</th>
<th>Strategic consequence to inspect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Continuous double auction</td>
<td>Buyers and sellers submit and accept bids and asks during the trading period.</td>
<td>Rapid feedback can aid price discovery; timing and order visibility affect bargaining.</td>
</tr>
<tr class="even">
<td>Posted-offer market</td>
<td>Sellers post take-it-or-leave-it prices and buyers choose among them.</td>
<td>Search and substitutability affect sellers’ pricing power.</td>
</tr>
<tr class="odd">
<td>Call market</td>
<td>Orders are pooled and matched at a scheduled clearing time.</td>
<td>Pooling reduces continuous speed competition; clearing and rationing rules determine trades.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A fish-market activity can assign private buyer values and seller costs, then vary supply across rounds, extending the experimental-market tradition of Smith (1962). Run the same underlying values under different trading rules. Compare prices, quantity, total surplus, and its division between buyers and sellers. Hold the economic environment as constant as possible so that differences can be traced to the rules under study.</p>
</div>
</div>
</div>
</section>
<section id="references-cited-in-this-chapter" class="level2">
<h2 data-anchor-id="references-cited-in-this-chapter">References cited in this chapter</h2>
<div class="reference">
<p>Bazerman, M. H., &amp; Samuelson, W. F. (1983). I won the auction but don’t want the prize. <em>Journal of Conflict Resolution, 27</em>(4), 618–634. https://doi.org/10.1177/0022002783027004003</p>
</div>
<div class="reference">
<p>Camerer, C. F. (2003). <em>Behavioral game theory: Experiments in strategic interaction</em>. Princeton University Press.</p>
</div>
<div class="reference">
<p>Camerer, C. F., Ho, T.-H., &amp; Chong, J.-K. (2004). A cognitive hierarchy model of games. <em>Quarterly Journal of Economics, 119</em>(3), 861–898. https://doi.org/10.1162/0033553041502225</p>
</div>
<div class="reference">
<p>Coricelli, G., &amp; Nagel, R. (2009). Neural correlates of depth of strategic reasoning in medial prefrontal cortex. <em>Proceedings of the National Academy of Sciences, 106</em>(23), 9163–9168. https://doi.org/10.1073/pnas.0807721106</p>
</div>
<div class="reference">
<p>Crawford, V. P., Costa-Gomes, M. A., &amp; Iriberri, N. (2013). Structural models of nonequilibrium strategic thinking: Theory, evidence, and applications. <em>Journal of Economic Literature, 51</em>(1), 5–62. https://doi.org/10.1257/jel.51.1.5</p>
</div>
<div class="reference">
<p>Keynes, J. M. (1936). <em>The general theory of employment, interest and money</em>. Macmillan.</p>
</div>
<div class="reference">
<p>Nagel, R. (1995). Unraveling in guessing games: An experimental study. <em>American Economic Review, 85</em>(5), 1313–1326.</p>
</div>
<div class="reference">
<p>Nash, J. F. (1950). Equilibrium points in n-person games. Proceedings of the National Academy of Sciences, 36(1), 48–49.</p>
</div>
<div class="reference">
<p>Schelling, T. C. (1960). <em>The strategy of conflict</em>. Harvard University Press.</p>
</div>
<div class="reference">
<p>Shubik, M. (1971). The dollar auction game: A paradox in noncooperative behavior and escalation. Journal of Conflict Resolution, 15(1), 109–111.</p>
</div>
<div class="reference">
<p>Smith, V. L. (1962). An experimental study of competitive market behavior. <em>Journal of Political Economy, 70</em>(2), 111–137. https://doi.org/10.1086/258609</p>
</div>
<div class="reference">
<p>Stahl, D. O., &amp; Wilson, P. W. (1995). On players’ models of other players: Theory and experimental evidence. <em>Games and Economic Behavior, 10</em>(1), 218–254. https://doi.org/10.1006/game.1995.1031</p>
</div>
<div class="reference">
<p>Staw, B. M. (1976). Knee-deep in the Big Muddy: A study of escalating commitment to a chosen course of action. Organizational Behavior and Human Performance, 16(1), 27–44.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark_dimmed">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "warrenchang/decisionbook";
    script.dataset.repoId = "R_kgDOTpqPRg";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOTpqPRs4DCa1q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../parts/part-4.html" class="pagination-link" aria-label="Part IV. Strategic and Social Decisions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Part IV. Strategic and Social Decisions</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/24-behavioral-game-theory-equilibrium-is-a-benchmark-not-a-portrait.html" class="pagination-link" aria-label="Coordination and Focal Points">
        <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Coordination and Focal Points</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Huanren Warren Zhang. All rights reserved.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/warrenchang/decisionbook/edit/main/chapters/23-strategic-interdependence-the-best-move-depends-on-other-minds.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/warrenchang/decisionbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/warrenchang/decisionbook/blob/main/chapters/23-strategic-interdependence-the-best-move-depends-on-other-minds.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>