<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Visible choices are only the endpoint. This book follows decisions in the making—from attention, interpretation, prediction, and valuation to influence, communication, negotiation, and the design of environments that make better judgment and action possible.">

<title>27&nbsp; Markets, Mispricing, and Bubbles – Decision in the Making</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/28-authority-groupthink-and-shared-responsibility.html" rel="next">
<link href="../chapters/26-social-norms-and-conformity-when-other-people-become-evidence.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d2ab3828f0446ed9f3a10bc4efc982a8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-4.html">Part IV. Strategic and Social Decisions</a></li><li class="breadcrumb-item"><a href="../chapters/27-markets-mispricing-and-bubbles.html"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Markets, Mispricing, and Bubbles</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Decision in the Making</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/warrenchang/decisionbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-to-use-this-book.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to Use This Book</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-to-read-evidence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to Read the Evidence in This Book</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part I. How a Choice Takes Shape</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-how-decisions-should-be-made-and-how-they-actually-are.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Normative, Descriptive, and Prescriptive</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-building-a-better-decision-alternatives-opportunity-cost-information-and-robustness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Building a Better Decision</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-attention-what-becomes-evidence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Limited Attention</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-the-predictive-mind-perception-is-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Predictive Mind</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-expectations-when-predictions-become-causes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Expectations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-valuation-how-options-become-worth-choosing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Valuation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-the-narrator-after-choice-why-reasons-are-not-always-causes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Narrator After Choice</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part II. Judgment Under Uncertainty</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-fast-and-frugal-thinking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Intuition and Deliberation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-what-feels-likely-availability-affect-and-resemblance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Availability, Affect, and Representativeness</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-beliefs-that-defend-themselves.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Confirmation Bias and Motivated Reasoning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-when-context-rewrites-comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Anchors, Halos, and Decoys</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-framing-when-the-same-facts-become-different-decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Framing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-accessibility-familiarity-and-ease.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Priming, Fluency, and Familiarity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-base-rates-conditional-probability-and-bayesian-updating.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Base Rates and Updating</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-samples-randomness-regression-and-calibration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Randomness and Overconfidence</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part III. Risk, Time, and Well-Being</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-risky-decision-making-a-probability-is-not-yet-a-feeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Risky Decision Making</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17-prospect-theory-gains-and-losses-begin-at-a-reference-point.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Prospect Theory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/18-decisions-from-experience-when-rare-events-are-not-encountered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Decisions From Experience</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/20-mental-accounting-money-is-fungible-minds-label-it.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Mental Accounting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/19-intertemporal-decision-making-why-later-loses-to-now.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Intertemporal Decision Making</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/21-habits-wanting-and-self-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Habits, Wanting, and Self-Control</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/22-deciding-for-a-better-life-satisfaction-connection-and-meaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Deciding for a Better Life</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part IV. Strategic and Social Decisions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/23-strategic-interdependence-the-best-move-depends-on-other-minds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Strategic Interdependence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/24-behavioral-game-theory-equilibrium-is-a-benchmark-not-a-portrait.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Coordination and Focal Points</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/25-cooperation-and-social-preferences-self-interest-is-not-the-only-payoff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Cooperation and Social Preferences</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/26-social-norms-and-conformity-when-other-people-become-evidence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Social Norms and Conformity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/27-markets-mispricing-and-bubbles.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Markets, Mispricing, and Bubbles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/28-authority-groupthink-and-shared-responsibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Authority, Groupthink, and Shared Responsibility</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/29-culture-and-identity-the-same-action-is-not-the-same-act.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Culture and Identity</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part V. Persuasion, Communication, and Connection</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/30-persuasion-changing-minds-means-updating-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Persuasion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/31-why-stories-move-minds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Why Stories Move Minds</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/32-building-an-evidence-aligned-message.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Building an Evidence-Aligned Message</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/33-communication-language-is-not-a-file-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Communication</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/34-connection-and-repair-warm-honesty-makes-truth-usable.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Connection and Repair</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part VI. Negotiating Joint Decisions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/35-negotiation-as-joint-decision-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Negotiation as Joint Decision Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/36-preparing-and-claiming-value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Distributive Negotiation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/37-creating-value-across-differences.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Integrative Negotiation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/38-designing-better-agreements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Designing Better Agreements</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../parts/part-7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part VII. Designing Better Decisions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/39-behavior-design-make-the-better-action-easier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Behavior Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/40-choice-architecture-the-environment-gets-a-vote.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Choice Architecture</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/41-decision-hygiene-build-a-process-that-can-learn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Decision Hygiene</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/42-data-driven-decision-making.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Deciding With Data and AI</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/appendix-a-rational-choice-and-decision-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Rational Choice and Decision Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/appendix-b-evolutionary-explanations-of-value-choice-and-rationality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Evolutionary Explanations of Value, Choice, and Rationality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/appendix-literature-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Conducting and Writing a Literature Review</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/appendix-e-how-behavioral-evidence-is-built.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Running an Experimental Study: From Question to Credible Evidence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/appendix-f-when-evidence-breaks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">When Evidence Breaks: The Replication Crisis and Research Integrity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/appendix-c-portable-course-tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Portable Tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/appendix-d-index-of-major-course-examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Index of Major Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../concept-index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Index of Concepts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About This Book</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-goals" id="toc-learning-goals" class="nav-link active" data-scroll-target="#learning-goals">Learning goals</a></li>
  <li><a href="#why-study-behavior-in-financial-markets" id="toc-why-study-behavior-in-financial-markets" class="nav-link" data-scroll-target="#why-study-behavior-in-financial-markets">Prices often move before you can trade</a>
  <ul class="collapse">
  <li><a href="#a-scheduled-announcement-unchanged-policy-can-be-surprising" id="toc-a-scheduled-announcement-unchanged-policy-can-be-surprising" class="nav-link" data-scroll-target="#a-scheduled-announcement-unchanged-policy-can-be-surprising">A scheduled announcement: unchanged policy can be surprising</a></li>
  <li><a href="#election-night-the-announcement-may-confirm-what-prices-already-reflect" id="toc-election-night-the-announcement-may-confirm-what-prices-already-reflect" class="nav-link" data-scroll-target="#election-night-the-announcement-may-confirm-what-prices-already-reflect">Election night: the announcement may confirm what prices already reflect</a></li>
  <li><a href="#challenger-prices-can-combine-dispersed-clues" id="toc-challenger-prices-can-combine-dispersed-clues" class="nav-link" data-scroll-target="#challenger-prices-can-combine-dispersed-clues">Challenger: prices can combine dispersed clues</a></li>
  </ul></li>
  <li><a href="#what-market-efficiency-doesand-does-notclaim" id="toc-what-market-efficiency-doesand-does-notclaim" class="nav-link" data-scroll-target="#what-market-efficiency-doesand-does-notclaim">What market efficiency does—and does not—claim</a></li>
  <li><a href="#historical-return-patterns-complicate-the-picture" id="toc-historical-return-patterns-complicate-the-picture" class="nav-link" data-scroll-target="#historical-return-patterns-complicate-the-picture">Historical return patterns complicate the picture</a>
  <ul class="collapse">
  <li><a href="#earnings-surprises-can-be-followed-by-drift" id="toc-earnings-surprises-can-be-followed-by-drift" class="nav-link" data-scroll-target="#earnings-surprises-can-be-followed-by-drift">Earnings surprises can be followed by drift</a></li>
  <li><a href="#size-value-momentum-and-reversal-ask-different-questions" id="toc-size-value-momentum-and-reversal-ask-different-questions" class="nav-link" data-scroll-target="#size-value-momentum-and-reversal-ask-different-questions">Size, value, momentum, and reversal ask different questions</a></li>
  </ul></li>
  <li><a href="#every-efficiency-test-is-a-joint-test" id="toc-every-efficiency-test-is-a-joint-test" class="nav-link" data-scroll-target="#every-efficiency-test-is-a-joint-test">Every efficiency test is a joint test</a></li>
  <li><a href="#limits-to-arbitrage-seeing-an-error-is-not-enough" id="toc-limits-to-arbitrage-seeing-an-error-is-not-enough" class="nav-link" data-scroll-target="#limits-to-arbitrage-seeing-an-error-is-not-enough">Limits to arbitrage: the costs and risks of correcting mispricing</a></li>
  <li><a href="#what-gives-an-asset-fundamental-value" id="toc-what-gives-an-asset-fundamental-value" class="nav-link" data-scroll-target="#what-gives-an-asset-fundamental-value">What gives an asset fundamental value?</a></li>
  <li><a href="#a-bubble-is-a-reinforcing-process-hypothesis" id="toc-a-bubble-is-a-reinforcing-process-hypothesis" class="nav-link" data-scroll-target="#a-bubble-is-a-reinforcing-process-hypothesis">How feedback can sustain a price bubble</a>
  <ul class="collapse">
  <li><a href="#strategic-resale-and-synchronization-risk" id="toc-strategic-resale-and-synchronization-risk" class="nav-link" data-scroll-target="#strategic-resale-and-synchronization-risk">How resale expectations can sustain a boom and crash</a></li>
  </ul></li>
  <li><a href="#historical-bubbles-recurring-feedback-different-institutions" id="toc-historical-bubbles-recurring-feedback-different-institutions" class="nav-link" data-scroll-target="#historical-bubbles-recurring-feedback-different-institutions">Historical bubbles: recurring feedback, different institutions</a>
  <ul class="collapse">
  <li><a href="#tulipmania-a-real-boom-surrounded-by-an-exaggerated-legend" id="toc-tulipmania-a-real-boom-surrounded-by-an-exaggerated-legend" class="nav-link" data-scroll-target="#tulipmania-a-real-boom-surrounded-by-an-exaggerated-legend">Early bubbles: tulips, shares, and state finance</a></li>
  <li><a href="#the-1920s-and-later-credit-booms" id="toc-the-1920s-and-later-credit-booms" class="nav-link" data-scroll-target="#the-1920s-and-later-credit-booms">Modern booms and crashes: innovation, credit, and fragile expectations</a></li>
  </ul></li>
  <li><a href="#one-laboratory-market-a-known-risk-neutral-benchmark-can-still-be-exceeded" id="toc-one-laboratory-market-a-known-risk-neutral-benchmark-can-still-be-exceeded" class="nav-link" data-scroll-target="#one-laboratory-market-a-known-risk-neutral-benchmark-can-still-be-exceeded">Experimental markets: making the valuation benchmark observable</a>
  <ul class="collapse">
  <li><a href="#a-finite-lived-asset-and-a-declining-benchmark" id="toc-a-finite-lived-asset-and-a-declining-benchmark" class="nav-link" data-scroll-target="#a-finite-lived-asset-and-a-declining-benchmark">A finite-lived asset and a declining benchmark</a></li>
  <li><a href="#flat-fundamentals-the-bubble-is-not-just-a-falling-value-task" id="toc-flat-fundamentals-the-bubble-is-not-just-a-falling-value-task" class="nav-link" data-scroll-target="#flat-fundamentals-the-bubble-is-not-just-a-falling-value-task">Bubbles with a constant fundamental-value benchmark</a></li>
  <li><a href="#experience-liquidity-and-trading-rules-change-the-result" id="toc-experience-liquidity-and-trading-rules-change-the-result" class="nav-link" data-scroll-target="#experience-liquidity-and-trading-rules-change-the-result">Experience, liquidity, and trading rules change the result</a></li>
  <li><a href="#expectations-and-the-strategies-behind-the-price-path" id="toc-expectations-and-the-strategies-behind-the-price-path" class="nav-link" data-scroll-target="#expectations-and-the-strategies-behind-the-price-path">Expectations and the strategies behind the price path</a></li>
  <li><a href="#lottery-payoffs-and-cognitive-reflection" id="toc-lottery-payoffs-and-cognitive-reflection" class="nav-link" data-scroll-target="#lottery-payoffs-and-cognitive-reflection">Payoffs and participants shape market behavior</a></li>
  </ul></li>
  <li><a href="#a-two-direction-bubble-dashboard" id="toc-a-two-direction-bubble-dashboard" class="nav-link" data-scroll-target="#a-two-direction-bubble-dashboard">Evaluating competing explanations for a boom</a></li>
  <li><a href="#investing-when-neither-prices-nor-forecasts-are-infallible" id="toc-investing-when-neither-prices-nor-forecasts-are-infallible" class="nav-link" data-scroll-target="#investing-when-neither-prices-nor-forecasts-are-infallible">Investing when neither prices nor forecasts are infallible</a></li>
  <li><a href="#practice-lab" id="toc-practice-lab" class="nav-link" data-scroll-target="#practice-lab">Practice Lab</a></li>
  <li><a href="#take-it-forward" id="toc-take-it-forward" class="nav-link" data-scroll-target="#take-it-forward">Take it forward</a></li>
  <li><a href="#optional-research-notes" id="toc-optional-research-notes" class="nav-link" data-scroll-target="#optional-research-notes">Optional research notes</a></li>
  <li><a href="#references-cited-in-this-chapter" id="toc-references-cited-in-this-chapter" class="nav-link" data-scroll-target="#references-cited-in-this-chapter">References cited in this chapter</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/warrenchang/decisionbook/edit/main/chapters/27-markets-mispricing-and-bubbles.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/warrenchang/decisionbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/warrenchang/decisionbook/blob/main/chapters/27-markets-mispricing-and-bubbles.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../parts/part-4.html">Part IV. Strategic and Social Decisions</a></li><li class="breadcrumb-item"><a href="../chapters/27-markets-mispricing-and-bubbles.html"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Markets, Mispricing, and Bubbles</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="prices-as-social-signals" class="quarto-section-identifier"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Markets, Mispricing, and Bubbles</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Prices as Social Signals</em></p>
<div id="chapter-27-start" class="chapter-epigraph">
<blockquote class="blockquote">
<p>“We simply attempt to be fearful when others are greedy and to be greedy only when others are fearful.”</p>
<p>— Warren Buffett, <a href="https://www.berkshirehathaway.com/letters/1986.html">1986 letter to Berkshire Hathaway shareholders</a>, 27 February 1987</p>
</blockquote>
</div>
<p><span id="opening-puzzle-earnings-beat-expectations"></span>A listed company reports earnings above the analyst consensus before the market opens. Should you buy immediately, wait, or do nothing?</p>
<p>The announcement sounds encouraging, but suppose you can place an order only five minutes after reading it. By then the price may already reflect the news. Buying makes sense only if that available price still leaves an attractive return for the risk and costs; recognizing a successful company is not enough.</p>
<p>The €20 note in <a href="#fig-finance-euro-efficiency" class="quarto-xref">Figure&nbsp;<span>27.1</span></a> poses a related puzzle: an obvious reward invites someone to collect it. In a market, that competition can change the available price before a slower investor acts. Before reading on, record when you learned the news, what further reaction you expect, and what costs your order would incur.</p>
<div id="fig-finance-euro-efficiency" class="quarto-float quarto-figure quarto-figure-center" alt="A twenty-euro note lies on pavement.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-finance-euro-efficiency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/finance-euro-note-found.png" class="img-fluid figure-img" style="width:55.0%" alt="A twenty-euro note lies on pavement.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-finance-euro-efficiency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.1: If you saw this €20 note on the ground, would you pick it up—and how long would such an obvious opportunity remain?
</figcaption>
</figure>
</div>
<div class="core-idea callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Core Idea
</div>
</div>
<div class="callout-body-container callout-body">
<p>Prices often incorporate news before an investor can trade on it. That makes obvious opportunities difficult to capture, but does not establish that every price is correct. To understand when errors survive, connect the evidence on price adjustment to investors’ beliefs, the risks of correcting mispricing, and the feedback through which prices themselves influence demand.</p>
</div>
</div>
<section id="learning-goals" class="level2">
<h2 data-anchor-id="learning-goals">Learning goals</h2>
<ul>
<li>Interpret rapid responses to news and explain why a correct reading of a headline may arrive too late to earn an abnormal return.</li>
<li>Distinguish rapid information incorporation, no free lunch, and fundamental-value accuracy; evaluate historical return patterns against risk, costs, and competing explanations.</li>
<li>Explain how cash flows, growth, discounting, and financing affect asset values and how limits to arbitrage can allow mispricing to persist.</li>
<li>Compare historical bubbles and experiments on experience, liquidity, expectations, and trading rules without treating their evidence as interchangeable.</li>
<li>Produce a falsifiable market memo and a two-direction bubble dashboard with a robust action.</li>
</ul>
</section>
<section id="why-study-behavior-in-financial-markets" class="level2">
<h2 data-anchor-id="why-study-behavior-in-financial-markets">Prices often move before you can trade</h2>
<p><span id="fast-price-discovery-is-possible"></span></p>
<p>The first question is empirical: what happens to prices when news arrives? A useful example has an identifiable surprise, a reliable release time, and prices observed closely enough to show the response. Three cases distinguish a scheduled announcement, information arriving throughout a night, and dispersed clues about an unexpected disaster.</p>
<section id="a-scheduled-announcement-unchanged-policy-can-be-surprising" class="level3">
<h3 data-anchor-id="a-scheduled-announcement-unchanged-policy-can-be-surprising">A scheduled announcement: unchanged policy can be surprising</h3>
<p>At 14:00 US Eastern time on September 18, 2013, the Federal Reserve announced that it would continue buying $40 billion of mortgage-backed securities and $45 billion of longer-term Treasury securities each month. Markets had expected a reduction. Maintaining the $85 billion total therefore changed expectations even though the policy itself was unchanged (<a href="https://www.federalreserve.gov/newsevents/pressreleases/monetary20130918a.htm">Federal Open Market Committee, 2013</a>).</p>
<p>In <a href="#fig-finance-fed-announcement" class="quarto-xref">Figure&nbsp;<span>27.2</span></a>, the S&amp;P 500 moves sharply at the announcement. The relevant comparison for a trader is the price available after learning the news, not the earlier price visible on the chart. An order submitted after reading and interpreting the announcement cannot retrospectively capture that initial jump.</p>
<div id="fig-finance-fed-announcement" class="quarto-float quarto-figure quarto-figure-center" alt="The S&amp;P 500 fluctuates before 14:00, rises sharply at the Fed announcement, and remains higher afterward. Opening and closing values are 1,705.48 and 1,725.52.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-finance-fed-announcement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/finance-fed-announcement.svg" class="img-fluid figure-img" style="width:100.0%" alt="The S&amp;P 500 fluctuates before 14:00, rises sharply at the Fed announcement, and remains higher afterward. Opening and closing values are 1,705.48 and 1,725.52.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-finance-fed-announcement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.2: S&amp;P 500 around the 14:00 Federal Reserve announcement on September 18, 2013. The published minute-by-minute chart shows rapid repricing; it cannot establish adjustment within seconds or milliseconds. Source: McKinsey Global Institute (2013), Exhibit 12, p.&nbsp;25; underlying attribution: Bloomberg and Wall Street Journal.
</figcaption>
</figure>
</div>
<p>This is the first lesson of the earnings puzzle: a favorable outcome matters through its unexpected component. Excellent earnings can disappoint a market that expected even more; unchanged policy can surprise a market that expected a change. The chart illustrates a rapid response to a particular announcement, not a complete test of whether all relevant information was incorporated correctly.</p>
</section>
<section id="election-night-the-announcement-may-confirm-what-prices-already-reflect" class="level3">
<h3 data-anchor-id="election-night-the-announcement-may-confirm-what-prices-already-reflect">Election night: the announcement may confirm what prices already reflect</h3>
<p>An election provides a different information process. Results arrive from many places over several hours, and traders update before any broadcaster declares a winner. The 2024 US election example in <a href="#fig-finance-election-night" class="quarto-xref">Figure&nbsp;<span>27.3</span></a> aligns a prediction-market contract with a broad equity-index futures price. The top panel records the price of a Kalshi contract paying $1 if Donald Trump or another Republican was inaugurated; the lower panel records E-mini S&amp;P 500 futures during the same night.</p>
<p>A contract price of 95 cents can be read approximately as a 95% market-implied probability under simplifying assumptions about risk preferences and trading frictions. It is neither vote share nor certainty, and its settlement condition matters. In the recorded minute closes, the price first reached 95 cents at 23:30, later dipped below it, and remained at or above it from 00:51 onward through the end of the observed series at 07:00. A threshold crossing and a sustained change convey different information.</p>
<div id="fig-finance-election-night" class="quarto-float quarto-figure quarto-figure-center" alt="Aligned election-night plots from 18:00 on November 5 to 06:00 on November 6. The Republican inauguration contract rises toward 100 cents, remaining at least 95 cents from 00:51. S&amp;P 500 futures rise unevenly from 5,820.25 to 5,942.75 index points.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-finance-election-night-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/finance-election-night.svg" class="img-fluid figure-img" style="width:100.0%" alt="Aligned election-night plots from 18:00 on November 5 to 06:00 on November 6. The Republican inauguration contract rises toward 100 cents, remaining at least 95 cents from 00:51. S&amp;P 500 futures rise unevenly from 5,820.25 to 5,942.75 index points.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-finance-election-night-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.3: Prices during the 2024 US election night. A: Kalshi PRES-2024-DJT, one-minute closing trades, on a 0–100-cent scale. B: Yahoo Finance’s ES=F continuous nearby E-mini S&amp;P 500 futures series, using each hourly bar’s opening price at its timestamp. Both panels use US Eastern time (UTC−5). Lines connect observations; the hourly futures data do not reveal the within-hour path. Sources: Kalshi and Yahoo Finance, as retained with the lecture data.
</figcaption>
</figure>
</div>
<p>The Associated Press declared Trump the winner at 05:34, after other organizations had already made projections (<a href="https://www.ap.org/the-definitive-source/behind-the-news/calling-the-2024-presidential-race-state-by-state/">Associated Press, 2024</a>). By then, much of the information behind the declaration was already public. A trader buying only upon reading that headline would therefore need to explain what remained unanticipated. Across the displayed 18:00–06:00 window, futures rose from 5,820.25 to 5,942.75, about 2.1%. That whole-window change is not an estimate of the effect of any one news item.</p>
<p><strong>Futures</strong> are contracts whose value is linked to an underlying asset or index. Equity-index futures can trade while the regular US stock session is closed, making them useful for observing overnight responses. The futures price need not equal the cash index because financing and expected dividends matter. The two panels also price different things: the inauguration outcome in one, and expectations about company earnings, policy, discount rates, and risk in the other. Their co-movement alone does not isolate which of these channels caused the equity response.</p>
<p>The lecture’s September 11, 2001 futures chart offers a related contrast: prices adjusted as the attacks unfolded, with a further sharp decline around the second plane’s impact (Siegel, 2008, Figure 13-1). The informational meaning of an unfolding event can change. Neither that chart nor hourly election observations identify response speed in milliseconds. The general point is that prices respond to arriving information, which need not coincide with the time a reader encounters a settled account of events.</p>
</section>
<section id="challenger-prices-can-combine-dispersed-clues" class="level3">
<h3 data-anchor-id="challenger-prices-can-combine-dispersed-clues">Challenger: prices can combine dispersed clues</h3>
<p>The space shuttle <em>Challenger</em> exploded at 11:39 a.m. on January 28, 1986; a Dow Jones newswire report followed at 11:47. All four major publicly traded contractors initially lost value. In <a href="#fig-finance-challenger" class="quarto-xref">Figure&nbsp;<span>27.4</span></a>, however, Morton Thiokol separates from the others. Measured from the previous day’s close, its stock fell 11.86%, compared with declines of roughly 2–3% for Lockheed, Martin Marietta, and Rockwell. Months later, the presidential commission identified failure of the booster O-ring seals supplied by Thiokol (Maloney &amp; Mulherin, 2003).</p>
<div id="fig-finance-challenger" class="wide-illustration quarto-float quarto-figure quarto-figure-center" alt="Intraday prices after the Challenger explosion. Thiokol's relative price falls toward 0.89 by the close, whereas the other three contractors end between about 0.95 and 0.98. Thiokol has a trading halt around noon.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-finance-challenger-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/finance-challenger-intraday.png" class="wide-illustration img-fluid figure-img" style="width:100.0%" alt="Intraday prices after the Challenger explosion. Thiokol's relative price falls toward 0.89 by the close, whereas the other three contractors end between about 0.95 and 0.98. Thiokol has a trading halt around noon.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-finance-challenger-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.4: Intraday prices of the four principal shuttle contractors after the Challenger explosion, relative to their opening prices; the daily returns in the text instead use the previous close. Morton Thiokol experiences the largest sustained decline. NYSE trading in Thiokol was halted from 11:52 to 12:44; a Nasdaq trade occurred at 12:36. A gap in trading is not an unchanged price. Source: Maloney and Mulherin (2003), Figure 1, reproduced in the lecture.
</figcaption>
</figure>
</div>
<p>Maloney and Mulherin found no single public report or clear insider-trading explanation that accounted for the market’s early discrimination. Their interpretation is that trading combined dispersed information and inference. This is evidence of successful price discovery in one episode, not evidence that the market already possessed the commission’s complete engineering explanation.</p>
<p>These cases make rapid information incorporation a serious benchmark. Financial markets have high stakes, professional participants, and rewards for identifying opportunities. They also raise the question that motivates behavioral finance: if competition is so powerful, why do some return patterns and apparent pricing errors survive?</p>
</section>
</section>
<section id="what-market-efficiency-doesand-does-notclaim" class="level2">
<h2 data-anchor-id="what-market-efficiency-doesand-does-notclaim">What market efficiency does—and does not—claim</h2>
<p><span id="the-20-note-and-three-meanings-of-efficiency"></span></p>
<p>The familiar joke says that a financial economist would not pick up the €20 note because someone would already have taken genuine money. Its useful intuition is competition for an obvious reward. Its mistake is treating the absence of opportunities as a premise that needs no observation. Search takes time and resources; a reward can remain precisely because it has not yet been noticed or is costly to collect.</p>
<p>The <strong>efficient market hypothesis</strong> concerns the incorporation of a specified information set into prices, conditional on a model of expected returns (Fama, 1970, 1991):</p>
<ul>
<li><strong>Weak form:</strong> the information set includes historical prices and returns.</li>
<li><strong>Semi-strong form:</strong> it includes publicly available information.</li>
<li><strong>Strong form:</strong> it includes all information, even private information—a much stronger benchmark.</li>
</ul>
<p>Three claims are easily confused:</p>
<ol type="1">
<li><strong>Information is incorporated quickly.</strong> Price responds to a specified signal.</li>
<li><strong>No free lunch.</strong> A public rule does not reliably earn abnormal return after appropriate risk and realistic costs.</li>
<li><strong>The price is right.</strong> Market price equals a well-defined fundamental value.</li>
</ol>
<p>The first two do not automatically establish the third. A price can be difficult to beat and still differ from a defensible estimate of fundamental value. Conversely, an apparent pricing error may offer no low-risk, implementable profit. Prices are also forecasts made under uncertainty: an outcome that later surprises investors does not by itself show that the earlier price was unreasonable.</p>
<p>Grossman and Stiglitz (1980) explain why perfect information incorporation is problematic when information is costly. If prices revealed all such information perfectly, nobody would pay to collect it; if nobody collected it, prices could not reveal it. Informed trading must be rewarded sufficiently to sustain information acquisition. The €20 analogy now returns as an equilibrium question: who searches, what does searching cost, and what rewards make the effort worthwhile?</p>
<p>Behavioral finance studies how beliefs, attention, preferences, and constraints affect investors and prices (Barberis &amp; Thaler, 2003). A biased investor does not imply a biased market, because other traders may offset the error. A market explanation therefore needs both a source of demand that moves prices and a reason competition does not eliminate its effect.</p>
</section>
<section id="historical-return-patterns-complicate-the-picture" class="level2">
<h2 data-anchor-id="historical-return-patterns-complicate-the-picture">Historical return patterns complicate the picture</h2>
<p>Rapid adjustment around some events can coexist with slower adjustment elsewhere. An <strong>event study</strong> compares returns around an identifiable event with returns predicted by a stated benchmark, then combines the differences across time or securities (MacKinlay, 1997). These differences are called abnormal returns; their cumulative sum shows whether the response is concentrated near the event or continues afterward.</p>
<section id="earnings-surprises-can-be-followed-by-drift" class="level3">
<h3 data-anchor-id="earnings-surprises-can-be-followed-by-drift">Earnings surprises can be followed by drift</h3>
<p>Rendleman, Jones, and Latané (1982) grouped companies by standardized unexpected quarterly earnings. In <a href="#fig-finance-earnings-evidence" class="quarto-xref">Figure&nbsp;<span>27.5</span></a>, the more favorable surprises are associated with higher cumulative abnormal returns. Crucially, the groups continue separating after the announcement rather than becoming flat once the initial response has occurred. The authors estimated that roughly half of the adjustment to unexpected earnings in their 1970s sample occurred during the following 90 days.</p>
<div id="fig-finance-earnings-evidence" class="wide-illustration quarto-float quarto-figure quarto-figure-center" alt="Ten earnings-surprise groups diverge around announcement day zero and continue separating over the following 90 days. The most favorable-surprise group rises to about 8 percent and the least favorable falls to about minus 9 percent. Curves are traced approximately from the source figure.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-finance-earnings-evidence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/finance-earnings-drift-redraw.svg" class="wide-illustration img-fluid figure-img" style="width:100.0%" alt="Ten earnings-surprise groups diverge around announcement day zero and continue separating over the following 90 days. The most favorable-surprise group rises to about 8 percent and the least favorable falls to about minus 9 percent. Curves are traced approximately from the source figure.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-finance-earnings-evidence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.5: Cumulative average excess returns around earnings announcements. Stocks are grouped into ten deciles by standardized unexpected earnings: decile 10 has the most favorable surprises and decile 1 the least favorable. Continued separation after day zero illustrates post-earnings-announcement drift. Approximately digitized from the lecture reproduction of Rendleman, Jones, and Latané (1982). These are historical portfolio averages, not returns guaranteed to an individual trader.
</figcaption>
</figure>
</div>
<p>This <strong>post-earnings-announcement drift</strong> challenges immediate and complete adjustment under the study’s benchmark. Limited attention, conservative updating, or gradual diffusion could contribute. Those explanations must still compete with risk, measurement, and implementation accounts. Knowing the historical average path is different from identifying, in real time, the firms and execution prices needed to earn it.</p>
</section>
<section id="size-value-momentum-and-reversal-ask-different-questions" class="level3">
<h3 data-anchor-id="size-value-momentum-and-reversal-ask-different-questions">Size, value, momentum, and reversal ask different questions</h3>
<p>The other lecture comparisons sort stocks by company size, valuation, or previous returns. <strong>Size</strong> refers to market capitalization. <strong>Value stocks</strong> have low prices relative to accounting measures such as earnings or book equity; <strong>growth stocks</strong> have high prices relative to those measures, often because investors expect strong future growth. Book value is an accounting measure of shareholders’ equity, not the current market value of the company.</p>
<p><strong>Dividend yield</strong> divides dividends per share by price. A high yield can reflect generous distributions or a depressed price because investors expect a dividend cut. Sorting jointly by size and valuation asks whether, for example, small value stocks behave differently from small growth stocks; it does not establish that size and value are interchangeable explanations.</p>
<p>A low price-to-earnings ratio is not proof of a bargain, and a successful growth company is not automatically a superior investment. Its success may already be expensive to buy. The lecture’s comparison of IBM and Standard Oil of New Jersey over 1950–2012 illustrates this distinction: stronger operating growth and greater price appreciation did not translate into the higher total shareholder return once dividends and purchase valuations were considered (Siegel, 2014). The example motivates a valuation question; two selected companies do not establish a general trading rule.</p>
<p>The evidence extends beyond individual examples. Fama and French (1998) found that high book-to-market value portfolios outperformed low book-to-market growth portfolios in 12 of 13 major markets during 1975–1995; the difference for their global portfolios averaged 7.68 percentage points annually. The result is historical and benchmark-dependent. It does not imply that value wins in every country, subperiod, or future market.</p>
<p><a href="#tbl-finance-anomalies" class="quarto-xref">Table&nbsp;<span>27.1</span></a> brings these findings together. Notice that momentum and reversal use different horizons: continuation over several months can coexist with reversal over several years. A useful explanation states the horizon and mechanism before seeing the price path.</p>
<div id="tbl-finance-anomalies" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-finance-anomalies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;27.1: Historical return patterns require competing explanations, not a single behavioral label
</figcaption>
<div aria-describedby="tbl-finance-anomalies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Pattern</th>
<th>Historical finding</th>
<th>Behavioral possibility</th>
<th>Rival account and implementation gate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Size</td>
<td>Smaller firms earned higher average returns in an early U.S. sample (Banz, 1981).</td>
<td>Neglect, limited attention, or segmented demand</td>
<td>Priced risk, illiquidity, micro-cap trading costs, sample sensitivity, and later attenuation</td>
</tr>
<tr class="even">
<td>Value</td>
<td>Stocks priced low relative to book value, earnings, or cash flow outperformed higher-priced “growth” stocks in influential U.S. and international samples (Fama &amp; French, 1992, 1998).</td>
<td>Extrapolation of growth stories or overreaction to past performance</td>
<td>Distress or another priced risk, changing definitions, portfolio construction, and costs</td>
</tr>
<tr class="odd">
<td>Momentum</td>
<td>Recent winners outperformed recent losers over intermediate horizons in the historical U.S. sample studied by Jegadeesh and Titman (1993).</td>
<td>Underreaction, gradual information diffusion, or herding</td>
<td>Time-varying risk, crash exposure, turnover, crowding, and trading costs</td>
</tr>
<tr class="even">
<td>Long-run reversal</td>
<td>Extreme prior losers outperformed prior winners over longer horizons in an early study (De Bondt &amp; Thaler, 1985).</td>
<td>Overreaction followed by correction</td>
<td>Benchmark and size effects, survivorship, overlapping formation periods, and implementability</td>
</tr>
<tr class="odd">
<td>Earnings drift</td>
<td>Returns continued in the direction of earnings surprises after announcements in the studied samples (Rendleman et al., 1982).</td>
<td>Conservatism, inattention, or gradual updating</td>
<td>Expected-return model, confounding news, measurement, tradable timing, liquidity, risk, and costs</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="every-efficiency-test-is-a-joint-test" class="level2">
<h2 data-anchor-id="every-efficiency-test-is-a-joint-test">Every efficiency test is a joint test</h2>
<p>The historical patterns raise a problem: to label a return abnormal, we must first say what return was expected. Suppose an asset earns 12%. That is not evidence of mispricing until we specify its risk, exposures, time period, benchmark, and costs.</p>
<p>The <strong>capital asset pricing model</strong> (CAPM) relates an asset’s expected excess return to its exposure to the market’s excess return. Its <strong>beta</strong> measures that exposure; an estimated <strong>alpha</strong> is the average return left unexplained by the fitted benchmark. Multifactor models allow several systematic exposures. An alpha can change when the benchmark changes, so it is not a model-free measure of skill. A more elaborate model is not automatically a better explanation either: its factors and tests need an economic justification (Sharpe, 1964; Fama &amp; French, 1993).</p>
<p>Fama (1991) emphasizes the <strong>joint-hypothesis problem</strong>: a test evaluates market efficiency together with an asset-pricing model. A rejection may reflect inefficient prices or an inadequate expected-return model. Unrealistic execution, omitted costs, or selection of the sample and statistic can further undermine an apparent trading opportunity.</p>
<div id="fig-behavioral-finance-audit" class="quarto-float quarto-figure quarto-figure-center" alt="A left-to-right evidence pipeline begins with a documented return pattern. It enters five alternative explanation boxes: priced risk, behavioral mispricing, market frictions, model misspecification, and data mining. The paths converge on an implementation gate for timing, liquidity, costs, capacity, and taxes, followed by an out-of-sample and post-publication test. The final outcome can be a bounded empirical regularity, an implementable strategy, or insufficient evidence.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-behavioral-finance-audit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/behavioral-finance-audit.svg" class="img-fluid figure-img" alt="A left-to-right evidence pipeline begins with a documented return pattern. It enters five alternative explanation boxes: priced risk, behavioral mispricing, market frictions, model misspecification, and data mining. The paths converge on an implementation gate for timing, liquidity, costs, capacity, and taxes, followed by an out-of-sample and post-publication test. The final outcome can be a bounded empirical regularity, an implementable strategy, or insufficient evidence.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-behavioral-finance-audit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.6: A documented return pattern passes through a joint-test audit before it can support an investment decision. Risk, mispricing, frictions, model error, and data mining remain competing explanations; implementation and post-publication evidence decide how much of the pattern survives.
</figcaption>
</figure>
</div>
<p><a href="#fig-behavioral-finance-audit" class="quarto-xref">Figure&nbsp;<span>27.6</span></a> separates explaining a return pattern from establishing whether it survives realistic trading conditions and new observations. An <strong>event study</strong> measures returns around a defined event against a stated expected-return model. The <a href="#advanced-research-track-auditing-an-event-study">optional research track</a> shows how to audit its timing, comparison, and uncertainty, using earnings announcements as an example.</p>
<div class="evidence-and-boundary-conditions callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Evidence Boundary: evaluating return anomalies
</div>
</div>
<div class="callout-body-container callout-body">
<p>A documented return pattern challenges a specified benchmark; it does not say whether the source is behavioral error, omitted risk, friction, model misspecification, or data mining. Finance offers thousands of securities, variables, transformations, and subperiods, so out-of-sample, after-cost, and post-publication evidence matters (Harvey et al., 2016). McLean and Pontiff (2016) examined 97 published return predictors. Returns were 26% lower outside the original samples and 58% lower after publication, relative to the original in-sample returns. Their comparison separates evidence of discovery bias from the additional decline associated with publication-informed trading. These averages do not establish that every anomaly disappears. A good company, a low price, and a high future return remain three different judgments.</p>
</div>
</div>
<p>The lecture’s longer value-return chart makes the same practical point: a favorable full-sample average can contain prolonged intervals of disappointing performance. A changing premium could reflect competition, changing risks, valuations, or the chosen sample. It cannot be attributed to arbitrage merely because the advantage became smaller. Once a rule is widely known, however, the original trading conditions cannot simply be assumed to persist.</p>
</section>
<section id="limits-to-arbitrage-seeing-an-error-is-not-enough" class="level2">
<h2 data-anchor-id="limits-to-arbitrage-seeing-an-error-is-not-enough">Limits to arbitrage: the costs and risks of correcting mispricing</h2>
<p>Recognizing an apparent error does not ensure that a trader can correct it. A strict arbitrage locks in a gain without a possible loss under the stated assumptions. For example, if one dollar buys €0.6455 and each euro buys ¥159.34, the indirect route yields about ¥102.85 per dollar. A direct rate of ¥100 would permit a currency round trip with a gain if all quoted trades could be executed simultaneously without fees or borrowing costs. In practice, bid–ask spreads, execution, and financing determine whether such a gap is usable. Many trades described as arbitrage instead bet on two prices eventually moving into a more defensible relation. That correction can take time and expose the trader to losses. Shleifer and Vishny (1997) show why informed traders may be unable or unwilling to make it happen:</p>
<ul>
<li><strong>Fundamental risk:</strong> the asset’s underlying value can worsen before convergence.</li>
<li><strong>Noise-trader risk:</strong> mispricing can become larger before it becomes smaller.</li>
<li><strong>Horizon risk:</strong> clients or managers may withdraw capital after interim losses.</li>
<li><strong>Short-sale constraints:</strong> borrowing can be unavailable, recalled, or expensive.</li>
<li><strong>Model risk:</strong> the apparent mispricing may be the analyst’s error.</li>
<li><strong>Transaction and funding costs:</strong> spreads, market impact, leverage, and margin calls can dominate.</li>
</ul>
<p>Professional incentives can shorten the horizon precisely when a long-horizon correction is expected. An arbitrageur can be right eventually and insolvent first. Behavioral market outcomes therefore require both a source of biased demand and a reason better-informed capital does not fully offset it.</p>
<p><span id="the-palm3com-case-visible-inconsistency-costly-correction"></span></p>
<p>On March 2, 2000, 3Com sold about 5% of its Palm subsidiary and announced an intention—subject to conditions—to distribute the remaining Palm shares to 3Com shareholders at roughly 1.5 Palm shares per 3Com share. Ignoring timing, taxes, and frictions, a 3Com share should therefore reflect the value of roughly 1.5 Palm shares plus its claim on 3Com’s other businesses.</p>
<p>After Palm’s first trading day, observed prices implied that the residual 3Com businesses were worth about negative $22 billion in Lamont and Thaler’s (2003) calculation. Simple addition makes that hard to defend. Yet Palm shares were scarce to borrow, shorting was costly and risky, and the distribution was delayed and conditional. The case is unusually strong evidence of relative-value mispricing—and equally strong evidence that a visible inconsistency need not create a riskless free lunch.</p>
<p>The lecture’s <strong>CUBA fund</strong> example connects these constraints back to news. After the December 2014 announcement of steps toward US–Cuba normalization, the Herzfeld Caribbean Basin Fund’s share price rose much more than the value of its portfolio. It did not own Cuban securities. Thaler (2016) uses the widening premium to illustrate demand apparently responding to a salient name and story. A closed-end fund’s shares trade separately from its portfolio, so net asset value is a useful comparison, but holders cannot generally redeem each share immediately for that value. The episode shows why rapid reaction and accurate valuation are separate questions; it does not make every closed-end-fund premium irrational.</p>
</section>
<section id="what-gives-an-asset-fundamental-value" class="level2">
<h2 data-anchor-id="what-gives-an-asset-fundamental-value">What gives an asset fundamental value?</h2>
<p>The Palm–3Com comparison uses two related claims to expose a price inconsistency. A broader bubble claim needs a benchmark for the asset itself. What benefits does ownership provide, and what are they worth today?</p>
<p>An <strong>asset</strong> is a resource or claim expected to provide economic benefits. A share of stock represents fractional ownership of a company; a bond promises payments to a lender, subject to default risk and its contractual terms. These are the equity and debt forms of financial capital. Banks channel deposits and other funding into loans, investment banks help firms issue and underwrite securities, arranging their sale and sometimes bearing the risk of unsold issues, and mutual funds and pension funds pool investments. These institutions matter for bubbles because they influence who can buy, how purchases are financed, and where losses go.</p>
<p>For a shareholder, profits can support dividends or share repurchases, or remain in the firm to finance investment, acquisitions, and debt repayment. Retained earnings create value when their use improves future benefits to shareholders sufficiently to justify the resources committed. Accounting earnings are therefore informative about value, but they are not identical to cash immediately available to an investor. Buying back shares is a distribution to selling shareholders, not the creation of additional operating profit.</p>
<p>Most claims that a market is overvalued face a harder problem: fundamental value is not printed beside the price. It depends on uncertain cash flows, risk, discounting, and a terminal value. A simplified discounted-cash-flow model adds the present value of the expected payments and the expected sale price at the end of the chosen horizon.</p>
<p>The adjustment must reflect both timing and risk. Discounting risky expected cash flows at a risk-free rate without a risk adjustment can misstate value; it overstates value when the claim requires a positive risk premium. The assumed terminal price also needs a valuation argument; extrapolating recent price gains simply moves the disputed belief to the end of the calculation. Before calling a price irrational, state the growth, margin, risk-adjustment, discount-rate, and terminal assumptions that would make it reasonable.</p>
<p>A constant-growth example makes the sensitivity concrete. In a hypothetical model where dividends grow indefinitely, a next-period dividend of €2, a required return of 8%, and growth of 3% imply a value of €40. Raising assumed growth to 4% increases it to €50. The arithmetic is exact within the model; the difficult work is defending the assumptions, especially growth continuing indefinitely. A low safe interest rate may support higher valuations, but risky equity generally requires a risk premium as well.</p>
<div id="math-asset-valuation">
<div class="research-lens mathematical-analysis callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Mathematical analysis: discounted cash flows and constant growth
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(D_t\)</span> denote the discount factor appropriate to a cash flow at horizon <span class="math inline">\(t\)</span>, and <span class="math inline">\(P_T\)</span> the ex-dividend terminal price. A simplified valuation is</p>
<p><span class="math display">\[
V_0=\sum_{t=1}^{T}D_tE(CF_t)+D_TE(P_T).
\]</span></p>
<p>Each <span class="math inline">\(D_t\)</span> must incorporate the timing and risk relevant to that claim. Equivalently, one can discount risk-adjusted certainty-equivalent cash flows at risk-free rates. The terminal price needs its own defensible valuation assumptions.</p>
<p>If next period’s expected dividend is <span class="math inline">\(d_1\)</span>, dividends grow indefinitely at rate <span class="math inline">\(g\)</span>, and the appropriate required return is a constant <span class="math inline">\(r&gt;g\)</span>, then</p>
<p><span class="math display">\[
V_0=\frac{d_1}{r-g}.
\]</span></p>
<p>The examples give <span class="math inline">\(2/(0.08-0.03)=40\)</span> and <span class="math inline">\(2/(0.08-0.04)=50\)</span>.</p>
</div>
</div>
</div>
</div>
<p>The <strong>price-to-earnings ratio</strong>, or P/E, divides the share price by earnings per share. It summarizes how much investors pay for one year’s reported or forecast earnings. It is not generally the number of years needed to recover the purchase price: that interpretation would require constant earnings paid out entirely, with discounting and risk ignored. A high P/E can reflect expected growth, low required returns, temporarily depressed earnings, or overoptimism. When earnings are negative or close to zero, the ratio becomes especially difficult to interpret.</p>
<p>Long historical price-and-earnings charts motivate the question of whether valuations have become detached from plausible future payouts. Shiller’s (1981) excess-volatility analysis compared observed price variation with a benchmark based on discounted subsequent dividends. Its interpretation depends on the assumptions about expected returns and the dividend process. The <strong>cyclically adjusted P/E ratio</strong>, or CAPE, divides real prices by average real earnings over the preceding ten years to reduce sensitivity to a single year’s earnings. Historical valuation peaks, including 1901, 1929, 1966, and 2000, are useful comparisons, not a calendar for the next crash (Shiller, 2000, 2013).</p>
</section>
<section id="a-bubble-is-a-reinforcing-process-hypothesis" class="level2">
<h2 data-anchor-id="a-bubble-is-a-reinforcing-process-hypothesis">How feedback can sustain a price bubble</h2>
<p>A <strong>price boom</strong> is an observed increase. A <strong>bubble</strong> is a sustained price deviation above a defensible fundamental-value benchmark. Identifying the latter requires more than showing that prices rose dramatically and later fell. Expectations about profits, discount rates, and risk may have changed, and our valuation model may be wrong. Behavioral accounts add a mechanism explaining how demand can reinforce the deviation.</p>
<p>A <strong>bubble diagnosis</strong> becomes more plausible when recent gains increase expectations of further gains, attract attention and financing, induce demand or strategic resale, and thereby validate the forecast temporarily (Shiller, 2000; Greenwood &amp; Shleifer, 2014).</p>
<div id="fig-asset-bubble-feedback" class="quarto-float quarto-figure quarto-figure-center" alt="Three boxes arranged in a loop show rising prices, expecting more gains, and more buying. A separate fundamentals box points to price; a dashed arrow from financing points to buying as an optional amplifier.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-asset-bubble-feedback-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/asset-bubble-feedback.svg" class="img-fluid figure-img" alt="Three boxes arranged in a loop show rising prices, expecting more gains, and more buying. A separate fundamentals box points to price; a dashed arrow from financing points to buying as an optional amplifier.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-asset-bubble-feedback-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.7: A possible reinforcing loop links rising prices, expectations of further gains, and more buying. Fundamentals affect price separately, and financing can amplify demand without being required for the loop. Supply, short selling, risk limits, and skeptical capital can weaken the process. Correction can be delayed by funding constraints and uncertainty about when others will act.
</figcaption>
</figure>
</div>
<p>The separate paths in <a href="#fig-asset-bubble-feedback" class="quarto-xref">Figure&nbsp;<span>27.7</span></a> allow a boom to begin with genuine innovation and later acquire a feedback component. Credit can amplify buying, but the loop does not require it.</p>
<section id="strategic-resale-and-synchronization-risk" class="level3">
<h3 data-anchor-id="strategic-resale-and-synchronization-risk">How resale expectations can sustain a boom and crash</h3>
<p>A buyer can believe that a price exceeds their own estimate of fundamental value and still purchase because they expect to resell to someone else at a higher price. The payoff then depends not only on cash flows but on beliefs about later buyers’ beliefs and on exiting before the correction. This is the recursive prediction problem in <a href="../chapters/23-strategic-interdependence-the-best-move-depends-on-other-minds.html#two-beauty-contests">Chapter 23’s beauty contest</a>, now with a financial consequence: accurately forecasting the next buyer can reward a trade the buyer would reject on cash-flow value alone.</p>
<p>This is often called the <strong>greater fool theory</strong>. The label is provocative, but the mechanism is precise: an anticipated resale price makes buying attractive even when the expected payouts from holding the asset do not. Disagreement and constraints on short selling can give this resale option value (Scheinkman &amp; Xiong, 2003). When expectations reverse, many holders may want to exit together. Buyers need not disappear at every conceivable price; the danger is that sufficient buyers are unavailable near the prices sellers expected, so even a modest sale can require a large price concession.</p>
<p>Skeptical traders face the mirror problem. Even when many privately judge the price fragile, each may be uncertain about when the others will act. Selling or shorting too early can be costly, and funding or career pressure can force an informed trader out before convergence. Abreu and Brunnermeier (2003) formalize how this <strong>synchronization risk</strong> can delay correction. Shared doubt is not the same as coordinated correction.</p>
<p><span id="how-a-boom-can-become-a-bubble-and-a-crash"></span></p>
<p>Historical accounts often describe an initial opportunity, widening participation, exuberance, distress, and panic (Kindleberger &amp; Aliber, 2011). A widely used teaching diagram calls these the stealth, awareness, mania, and blow-off phases (Rodrigue, n.d.). Treat that sequence as a possible feedback process:</p>
<ol type="1">
<li><strong>An opportunity attracts buyers.</strong> A technology, policy change, new market, or financing innovation can improve genuine prospects.</li>
<li><strong>The price rise recruits further demand.</strong> Early gains attract attention, imitation, and extrapolation. Successful buyers may appear more knowledgeable than they are.</li>
<li><strong>Financing and resale expectations sustain participation.</strong> Rising collateral values can permit more borrowing, while people who doubt the valuation may still expect to sell at a profit.</li>
<li><strong>The process reverses.</strong> Disappointing cash flows, tighter funding, increased supply, or a change in expectations can reduce demand. Falling collateral values and margin calls may then force further selling.</li>
</ol>
<p>A temporary recovery during the decline can encourage the belief that the market is returning to normal. But the labels in a cycle diagram are usually assigned with hindsight. They do not identify today’s phase reliably, establish that early buyers were informed, or imply that every boom follows the same path. Stories such as the shoeshine boy whose stock tips supposedly prompted Joseph Kennedy to exit before 1929 express concern about widespread participation; they are anecdotes, not verified trading signals.</p>
</section>
</section>
<section id="historical-bubbles-recurring-feedback-different-institutions" class="level2">
<h2 data-anchor-id="historical-bubbles-recurring-feedback-different-institutions">Historical bubbles: recurring feedback, different institutions</h2>
<p><a href="#tbl-historical-bubbles" class="quarto-xref">Table&nbsp;<span>27.2</span></a> compares episodes across several centuries, distinguishing speculative asset-price booms from broader credit booms and crises. The dates identify broad episodes, not identical national turning points. The central comparison is what investors were buying, what financed the expansion, and how a reversal could spread losses.</p>
<div id="tbl-historical-bubbles" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-historical-bubbles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;27.2: Historical episodes, with distinctions between asset-price and credit booms. Overview: Kindleberger and Aliber (2011); the detailed cases below supply additional evidence and qualifications.
</figcaption>
<div aria-describedby="tbl-historical-bubbles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Episode</th>
<th>What expanded</th>
<th>What the comparison teaches</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dutch tulipmania, 1636–1637</td>
<td>Trading in rare bulbs and contracts for future delivery</td>
<td>Resale expectations can develop around a collectible; later stories can exaggerate participation and economic damage.</td>
</tr>
<tr class="even">
<td>South Sea Company, Britain, 1720</td>
<td>Company shares linked to government-debt conversion and overseas-trade expectations</td>
<td>Public backing and sophisticated investors do not prevent a speculative price rise.</td>
</tr>
<tr class="odd">
<td>Mississippi scheme, France, 1719–1720</td>
<td>Company shares, public-debt conversion, and banknote issuance under John Law</td>
<td>Supporting asset prices through money creation can connect speculative demand to the monetary system.</td>
</tr>
<tr class="even">
<td>U.S. equities, 1927–1929</td>
<td>Shares during an economic and technological expansion, including purchases on margin</td>
<td>Genuine prosperity can coexist with fragile financing; a crash and a depression require separate explanations.</td>
</tr>
<tr class="odd">
<td>Lending to Mexico and other developing economies, 1970s</td>
<td>International bank lending, followed by the debt crisis beginning in 1982</td>
<td>Optimism about repayment and continued refinancing can create vulnerability without a stock-market bubble.</td>
</tr>
<tr class="even">
<td>Japanese property and equities, late 1980s</td>
<td>Land and share valuations supported by credit</td>
<td>Collateral values and lending can reinforce one another and leave prolonged balance-sheet problems.</td>
</tr>
<tr class="odd">
<td>Finland, Norway, and Sweden, late 1980s into early 1990s</td>
<td>Credit, property, and equity booms followed by banking crises, with different national timing</td>
<td>Liberalized credit markets can expand faster than the capacity to assess and absorb risk.</td>
</tr>
<tr class="even">
<td>Mexico, early 1990s, and several Asian economies, 1992–1997</td>
<td>Capital inflows; property, equity, and credit expansion in Thailand, Malaysia, Indonesia, and other Asian economies</td>
<td>Reversals of foreign financing add currency and refinancing risks. Mexico’s 1994–1995 crisis is distinct from the Asian crisis beginning in 1997.</td>
</tr>
<tr class="odd">
<td>U.S. internet and technology shares, 1995–2000</td>
<td>Valuations and issuance around the commercialization of the internet</td>
<td>A transformative technology can succeed while prices paid for claims on its profits prove excessive.</td>
</tr>
<tr class="even">
<td>Housing and credit, 2000s</td>
<td>Property and lending booms in the United States, Britain, Spain, Ireland, and Iceland, among others</td>
<td>Debt and interconnected intermediaries can turn a property correction into a wider financial crisis; exposures differed across countries.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="tulipmania-a-real-boom-surrounded-by-an-exaggerated-legend" class="level3">
<h3 data-anchor-id="tulipmania-a-real-boom-surrounded-by-an-exaggerated-legend">Early bubbles: tulips, shares, and state finance</h3>
<p>Rare tulips were valued as cultivated curiosities and markers of taste in the seventeenth-century Netherlands. During 1636–1637, trading extended to contracts for bulbs still in the ground. A buyer could therefore participate partly because another collector or trader might later pay more. When confidence in continued buying failed in early 1637, prices collapsed and disputes arose over honoring contracts.</p>
<p>The familiar version depicts an entire nation gambling away its wealth. Goldgar’s (2007) archival research instead finds a much more limited network of participants and much less evidence of economy-wide ruin. Exceptional quoted prices should not be treated as typical completed cash transactions. The episode illustrates speculative resale, the social formation of value, and the importance of trust in promises.</p>
<p><span id="the-south-sea-bubble-newton-could-sell-early-and-still-lose-later"></span></p>
<p>The South Sea Company combined a role in managing British government debt with expectations of overseas trade. Its privileges included participation in the trade in enslaved Africans. The scheme’s appeal cannot be understood simply as investment in a productive business: debt conversion, political support, and expectations about future share demand also mattered. In 1720 its share price rose dramatically before collapsing (Kindleberger &amp; Aliber, 2011; Odlyzko, 2020).</p>
<p>Isaac Newton’s investment history makes the timing problem vivid. An experienced investor, he sold South Sea holdings during the rise and made a substantial profit, then bought back at much higher prices and suffered large losses. Odlyzko’s (2020) reconstruction supports that sequence but also shows why a single exact loss figure is misleading: losses relative to initial wealth differ from losses relative to the wealth Newton could have retained after his early gains. The often-repeated £20,000 is an estimate, and he did not end bankrupt.</p>
<p>A successful exit can still leave an investor vulnerable to regret: watching the price continue to rise can turn a realized gain into a perceived missed opportunity.</p>
<p><span id="the-mississippi-scheme-speculation-linked-to-money-creation"></span></p>
<p>In France, John Law’s system combined a trading company associated with Mississippi development, conversion of public debt into equity, and a bank issuing paper money. The arrangement promised a radical improvement in state finance. As share prices rose, supporting them became entangled with creating additional money. Velde (2003) argues that Law supported equity at an excessively high level, producing uncontrolled money creation; the system unraveled in 1720.</p>
<p>The comparison with South Sea matters because similar price trajectories can arise through different institutions. In the French case, demand for shares, the financing of the state, and confidence in money were directly connected. Explaining the crash therefore requires understanding those obligations as well as investor enthusiasm.</p>
</section>
<section id="the-1920s-and-later-credit-booms" class="level3">
<h3 data-anchor-id="the-1920s-and-later-credit-booms">Modern booms and crashes: innovation, credit, and fragile expectations</h3>
<p>The U.S. boom of the late 1920s accompanied real economic growth and enthusiasm for technologies and companies. Excitement extended across telephone, electrical-manufacturing, and radio companies. Buying shares on margin added a separate vulnerability: investors financed part of their purchases with borrowed money and could face demands for additional funds when prices fell. The October 1929 crash damaged wealth and confidence, but the subsequent Depression also involved banking panics, monetary contraction, and other failures. Treating the crash as its complete explanation misses those transmission mechanisms (Richardson et al., 2013).</p>
<p>Later episodes broaden the lesson beyond shares. During the 1970s, international banks expanded lending to Latin America. Higher interest rates, recession, and refinancing difficulties helped turn accumulated debt into a crisis; Mexico announced in August 1982 that it could no longer service its debt (Sims &amp; Romero, 2013). Japan and the Nordic countries subsequently experienced property, equity, and credit booms, while the 1990s added major reversals of international capital flows. These episodes direct attention to who owes whom, in which currency, and at what maturity. A rising asset price and an expanding stock of debt are different facts, but their interaction can make the system fragile.</p>
<p><span id="one-field-episode-dot-com-innovation-and-extreme-expectations"></span></p>
<p>From the January 3, 1995 close of 743.58 to the March 10, 2000 peak close of 5,048.62, the NASDAQ Composite rose about 579%. By October 9, 2002, it closed at 1,114.11—a 77.9% decline from the peak (Federal Reserve Bank of St.&nbsp;Louis, 2026). Young internet firms faced genuine innovation, profound valuation uncertainty, restricted share supply, disagreement, and optimistic growth narratives (Ofek &amp; Richardson, 2003).</p>
<p>Ofek and Richardson (2003) report that their equal-weighted internet index gained more than 1,000% from early 1998 through February 2000, then lost those gains by the end of 2000. Their evidence connects optimistic beliefs and short-sale restrictions to high prices, and the release of previously restricted shares to subsequent declines. The success of the internet as a technology did not guarantee that buyers would earn satisfactory returns at the prices they paid.</p>
<p>Beliefs about value and beliefs about the next price also diverged. Shiller (2013) reports that in spring 2000 only about 33% of institutional respondents and 28% of individual respondents in the Yale surveys regarded the market as not overvalued, although most expected it to rise over the following year. The responses show how widespread valuation doubts can coexist with expectations of further gains. Resale expectations and uncertainty about timing can sustain participation even when confidence in fundamental value is weak.</p>
<p><span id="housing-when-a-correction-reaches-balance-sheets"></span></p>
<p>The U.S. housing boom connected a familiar asset to a complicated financing system. Buyers could justify higher prices through rents, housing services, limited supply, or lower financing costs, but expectations of continued appreciation also made purchasing and refinancing appear safer. A comparison with longer historical patterns asks whether rents, incomes, construction costs, and financing conditions plausibly supported the increase. Population growth alone cannot settle it, and national indexes conceal substantial regional differences.</p>
<p>Mortgage borrowing expanded alongside prices. Loans were packaged into securities held across the financial system, and many institutions depended on funding that had to be renewed frequently. When housing prices fell, refinancing became more difficult and mortgage losses increased. Uncertainty about who held the losses weakened confidence in counterparties and funding markets (Weinberg, 2013).</p>
<p>The damage spread beyond housing. The S&amp;P 500 lost about 57% between its October 2007 peak and March 2009 trough (Rich, 2013). Equity markets across many countries also fell during 2008. Comparing those declines requires specifying dates, price versus total returns, and currency. A foreign investor’s dollar return can differ sharply from the same market’s local-currency return. The explanatory task is to trace exposures and financing, rather than assume that simultaneous losses establish identical national bubbles.</p>
<p><span id="a-crash-does-not-settle-the-bubble-diagnosis"></span></p>
<p>On October 19, 1987, the Dow Jones Industrial Average fell 22.6% in one day. Proposed explanations include changing economic expectations, portfolio-insurance selling, and strains in market liquidity and trading systems (Bernhardt &amp; Eckblad, 2013). A later rebound cannot establish that the preceding valuation was correct, just as a crash alone cannot prove that it was a bubble.</p>
</section>
</section>
<section id="one-laboratory-market-a-known-risk-neutral-benchmark-can-still-be-exceeded" class="level2">
<h2 data-anchor-id="one-laboratory-market-a-known-risk-neutral-benchmark-can-still-be-exceeded">Experimental markets: making the valuation benchmark observable</h2>
<p>Field data rarely reveal fundamental value with certainty. Laboratory markets can define the dividend distribution, asset life, information, cash, short-selling rules, and trading institution. In the classic Smith, Suchanek, and Williams design, a finite-lived asset paid a dividend after each period. With no final redemption and negligible discounting over the short experimental session, the <strong>risk-neutral expected-dividend benchmark</strong> is the expected dividend per period multiplied by the number of periods remaining. Prices in many baseline markets nevertheless rose above the benchmark and later fell (Smith et al., 1988; Porter &amp; Smith, 2003).</p>
<section id="a-finite-lived-asset-and-a-declining-benchmark" class="level3">
<h3 data-anchor-id="a-finite-lived-asset-and-a-declining-benchmark">A finite-lived asset and a declining benchmark</h3>
<p>In a common baseline parameterization, the asset lasts 15 periods and each period’s dividend is equally likely to be 0, 8, 28, or 60 cents. Averaging the four equally likely dividends gives 24 cents per period. Immediately before trading in the first period, 15 dividends remain, so the risk-neutral benchmark is 360 cents. It falls by 24 cents after each dividend opportunity, reaches 24 cents before the final dividend, and is zero after the asset expires. For comparison, an asset that pays 12 or 20 cents with equal probability has an expected dividend of 16 cents and an initial 15-period benchmark of $2.40.</p>
<p>Participants begin with cash and shares. In a <strong>double auction</strong>, buyers can submit bids and sellers can submit asks while observing other offers. Under the classroom implementation used here, an incoming order that crosses the best standing offer executes at that standing offer’s price. A trader can buy to collect remaining dividends or to sell again during the experiment. A resale changes who receives those dividends; it does not add dividends to the asset.</p>
<p>Prices in many inexperienced markets begin below the expected-dividend benchmark, rise above it, and fall late in the session. Initial underpricing could reflect risk aversion or uncertainty about the task and other traders. Later overpricing cannot be explained merely by learning that the asset has a larger expected dividend: the distribution is already given.</p>
<p>Bubble-like paths are not confined to groups of a dozen participants. Williams (2008) reports large computerized classroom markets, including one with 304 traders that exhibited a substantial boom and crash. Adding traders therefore does not automatically create independent judgments or eliminate feedback.</p>
</section>
<section id="flat-fundamentals-the-bubble-is-not-just-a-falling-value-task" class="level3">
<h3 data-anchor-id="flat-fundamentals-the-bubble-is-not-just-a-falling-value-task">Bubbles with a constant fundamental-value benchmark</h3>
<p>Many real assets do not mechanically lose one dividend’s expected value each short trading period. A useful experimental design therefore pays interest on cash, provides an expected dividend each period, and adds a final redemption payment. Choosing the redemption payment appropriately offsets the shortening dividend horizon, so the risk-neutral discounted benchmark stays constant.</p>
<p>For example, an expected dividend of $0.70 with 10% interest per period and one of $1.40 with 20% interest both imply a constant benchmark of $7 under this design. These are experimental per-period rates, not annual market rates. They also produce different flows of dividends and interest into traders’ accounts even though the benchmark is unchanged.</p>
<div id="math-market-benchmarks">
<div class="research-lens mathematical-analysis callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Mathematical analysis: declining and constant market benchmarks
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Without final redemption and with negligible discounting, an asset with expected dividend <span class="math inline">\(d\)</span> and <span class="math inline">\(k\)</span> periods remaining has the risk-neutral benchmark</p>
<p><span class="math display">\[
FV_t=kd.
\]</span></p>
<p>In the baseline example, <span class="math inline">\((0+8+28+60)/4=24\)</span> cents and <span class="math inline">\(15\times24=360\)</span> cents initially.</p>
<p>For the constant-benchmark design, let cash earn interest <span class="math inline">\(r&gt;0\)</span> per period, let the expected dividend be <span class="math inline">\(d\)</span>, and set final redemption to <span class="math inline">\(R=d/r\)</span>. With <span class="math inline">\(k\)</span> periods remaining,</p>
<p><span class="math display">\[
FV_t=\sum_{j=1}^{k}\frac{d}{(1+r)^j}+\frac{d/r}{(1+r)^k}=\frac{d}{r}.
\]</span></p>
<p>Thus <span class="math inline">\(d=\$0.70\)</span> with <span class="math inline">\(r=10\%\)</span> and <span class="math inline">\(d=\$1.40\)</span> with <span class="math inline">\(r=20\%\)</span> both give <span class="math inline">\(d/r=\$7\)</span>. The identity holds under the stated risk-neutral discounting and redemption assumptions.</p>
</div>
</div>
</div>
</div>
<p>Bostian and Holt (2009) describe this design and report prices rising above the flat benchmark. Their higher-payment example illustrates how faster wealth accumulation can support larger price deviations. Because the dividend and interest processes change together, that comparison should not be described as a pure manipulation of initial cash. Experiments that vary initial cash directly provide complementary evidence (Caginalp et al., 1998).</p>
</section>
<section id="experience-liquidity-and-trading-rules-change-the-result" class="level3">
<h3 data-anchor-id="experience-liquidity-and-trading-rules-change-the-result">Experience, liquidity, and trading rules change the result</h3>
<p>Repeated experience often reduces bubbles in the same environment (Dufwenberg et al., 2005). That finding is more specific than saying that markets inevitably learn. Hussam et al.&nbsp;(2008) rekindled bubbles among experienced traders after changing liquidity and dividend uncertainty. Deck et al.&nbsp;(2014) introduced overlapping generations: new participants arrived with cash and older participants exited with cash, producing recurring price rises and falls within a single asset’s life. What the market has learned can change when its participants, resources, or rules change.</p>
<p>The <strong>cash-to-fundamental-value ratio</strong> compares cash available in a market with the aggregate benchmark value of its outstanding shares. More cash can allow optimistic traders to express greater demand without any increase in expected payouts. There is no universal ratio above which a bubble must occur. Prices depend on how participants use their purchasing power and on the institution through which bids become transactions.</p>
<p>The interventions in <a href="#tbl-bubble-experimental-conditions" class="quarto-xref">Table&nbsp;<span>27.3</span></a> change different parts of the market: available cash, borrowing, payout timing, or short selling.</p>
<div id="tbl-bubble-experimental-conditions" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bubble-experimental-conditions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;27.3: Experimental conditions that alter price formation. Results are conditional on the respective designs, not universal prescriptions.
</figcaption>
<div aria-describedby="tbl-bubble-experimental-conditions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Condition studied</th>
<th>Main result in the cited setting</th>
<th>What the result can establish</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>More initial cash relative to assets</td>
<td>Prices increased when cash was more abundant (Caginalp et al., 1998).</td>
<td>Purchasing power can change prices with the dividend process held fixed.</td>
</tr>
<tr class="even">
<td>Looser borrowing constraints</td>
<td>Relaxing credit constraints generated larger bubbles; higher exogenous income also raised prices (Coppock et al., 2021).</td>
<td>Borrowing capacity is one route through which demand expands.</td>
</tr>
<tr class="odd">
<td>Dividends paid later</td>
<td>Bubbles were less prevalent when dividends were concentrated at the end of the horizon (Smith et al., 2000).</td>
<td>Payment timing changes cash available for reinvestment and may help coordinate expectations; these channels need to be distinguished.</td>
</tr>
<tr class="even">
<td>Short selling permitted</td>
<td>Short-sale capacity reduced overpricing but could produce prices below the benchmark (Haruvy &amp; Noussair, 2006).</td>
<td>Giving pessimistic views greater trading capacity need not make prices exactly correct.</td>
</tr>
<tr class="odd">
<td>Resale ruled out</td>
<td>Bubbles and crashes still occurred when participants could buy or sell but could not speculate by buying and reselling (Lei et al., 2001).</td>
<td>Strategic resale is not necessary for every experimental bubble.</td>
</tr>
<tr class="even">
<td>Another useful trading activity available</td>
<td>Much of the excess asset trading diminished when participants had another market activity (Lei et al., 2001).</td>
<td>The opportunity cost of attention and the laboratory’s implicit invitation to trade affect behavior.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The no-resale result is particularly demanding for a pure greater-fool explanation. If traders cannot profit by passing the asset on, some other source of demand must account for the deviation. Confusion, valuation errors, preferences, and features of the trading task remain candidates. Tucker and Xu (2024) reproduced bubbles in a related no-speculation design but highlighted consequences of the restrictions themselves, including asymmetric endowments and changing cash-to-asset ratios and scarcity as trading proceeds.</p>
</section>
<section id="expectations-and-the-strategies-behind-the-price-path" class="level3">
<h3 data-anchor-id="expectations-and-the-strategies-behind-the-price-path">Expectations and the strategies behind the price path</h3>
<p>Holt et al.&nbsp;(2017) elicited short-term price forecasts and found that predictions typically trailed prices during the rise and remained above them during the decline. Forecast paths were too flat and did not generally anticipate the turning point. Haruvy et al.&nbsp;(2007) likewise show why measuring expectations adds information beyond observing transactions: the same purchase can reflect different views about value and future resale prices.</p>
<p>Different strategies can sustain the same path. A passive or fundamental-value trader buys below the benchmark and sells above it. A feedback trader increases demand after price rises and reduces it after falls, potentially amplifying the trend. A speculator may buy above a current value estimate when expecting a still higher next price. Haruvy and Noussair’s (2006) rule classified behavior only when a trader’s highest consistency score reached at least 8 of 15 periods; ties received fractional weights. Across 18 sessions with nine inexperienced participants each, the 162 trader classifications in <a href="#tbl-bubble-strategies" class="quarto-xref">Table&nbsp;<span>27.4</span></a> split across several patterns:</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Classification details
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="tbl-bubble-strategies" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bubble-strategies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;27.4: Rule-based behavioral classifications in Haruvy and Noussair (2006): 162 classifications from 18 sessions, fractional allocation of ties, and a highest consistency score of at least 8 of 15 periods.
</figcaption>
<div aria-describedby="tbl-bubble-strategies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Strategy classification</th>
<th style="text-align: right;">Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Feedback / momentum-consistent</td>
<td style="text-align: right;">36.5%</td>
</tr>
<tr class="even">
<td>Passive / fundamental-value-consistent</td>
<td style="text-align: right;">33.1%</td>
</tr>
<tr class="odd">
<td>Speculator / next-price-consistent</td>
<td style="text-align: right;">25.4%</td>
</tr>
<tr class="even">
<td>Other or unclassified</td>
<td style="text-align: right;">4.9%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
</div>
<div id="fig-bubble-trader-strategies-redraw" class="quarto-float quarto-figure quarto-figure-center" alt="Horizontal bars show feedback or momentum-consistent behavior at thirty-six point five percent, passive or fundamental-value-consistent behavior at thirty-three point one percent, speculator or next-price-consistent behavior at twenty-five point four percent, and other or unclassified behavior at four point nine percent.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bubble-trader-strategies-redraw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/bubble-trader-strategies-redraw.svg" class="img-fluid figure-img" style="width:100.0%" alt="Horizontal bars show feedback or momentum-consistent behavior at thirty-six point five percent, passive or fundamental-value-consistent behavior at thirty-three point one percent, speculator or next-price-consistent behavior at twenty-five point four percent, and other or unclassified behavior at four point nine percent.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bubble-trader-strategies-redraw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.8: The chart reports 36.5% feedback or momentum-consistent behavior, 33.1% passive or fundamental-value-consistent behavior, 25.4% speculator or next-price-consistent behavior, and 4.9% other or unclassified behavior. Haruvy and Noussair (2006) report 162 rule-based classifications in 18 sessions, with fractional allocation of ties and a highest consistency score of at least 8 of 15 periods.
</figcaption>
</figure>
</div>
<p>The mixture in <a href="#fig-bubble-trader-strategies-redraw" class="quarto-xref">Figure&nbsp;<span>27.8</span></a> shows several patterns of trading within the same experimental design. They help organize competing explanations for the price path, without establishing that every trader assigned a label used the same reasoning.</p>
</section>
<section id="lottery-payoffs-and-cognitive-reflection" class="level3">
<h3 data-anchor-id="lottery-payoffs-and-cognitive-reflection">Payoffs and participants shape market behavior</h3>
<p>The market rules are only part of the explanation: the payoff distribution and the people trading also matter. Two assets can have the same expected dividend while offering very different payoff distributions. In Ackert et al.&nbsp;(2006), a standard asset paid $0.50, $0.90, or $1.20 with probabilities 0.48, 0.48, and 0.04, giving an expected dividend of $0.72. A lottery asset paid $18 with probability 0.04 and zero otherwise, also averaging $0.72. In markets that developed bubbles, traders paid more for the lottery asset. Financing purchases from their own available funds and allowing short sales moderated the price run-ups.</p>
<p>Equal expected payouts do not imply that every preference model assigns equal value. Attraction to positively skewed payoffs and overweighting a small chance of a large gain are possible interpretations. The example connects asset trading to the treatment of small probabilities in <a href="../chapters/17-prospect-theory-gains-and-losses-begin-at-a-reference-point.html">Prospect Theory</a>.</p>
<p>Individual differences also matter without translating automatically into market accuracy. Corgnet et al.&nbsp;(2015) found that higher cognitive reflection test scores were associated with higher earnings and trading more consistent with fundamentals. Bubbles occurred even when participants had earned their initial endowments through a task, although trading volume and earnings dispersion were higher with house money.</p>
<p><span id="gender-context-and-a-distinct-hormonal-intervention"></span></p>
<p>Market composition raises a related question about how individual differences combine in trading. The suggestion that “Lehman Sisters” would have avoided the crisis is a memorable prompt for a hypothesis. The experiments supply a more conditional answer. Eckel and Füllbrunn (2015) found larger bubbles in all-male than all-female markets in their declining-value design. Their later study did not find a significant difference when gender composition was obscured (Eckel &amp; Füllbrunn, 2017). Holt et al.&nbsp;(2017) found similar bubbles across gender groups with flat fundamentals and unobtrusive sorting, but larger bubbles among men in a declining-value robustness treatment.</p>
<p>Wang et al.&nbsp;(2018) further found that all-female groups in China produced bubbles comparable to those in all-male groups, and larger than those in all-female U.S. groups. Cross-country comparisons also change more than one contextual feature and cannot isolate “culture” as if it were a randomly assigned treatment.</p>
<p>Nadler et al.&nbsp;(2018) tested a different question by experimentally administering testosterone or placebo to male participants. Testosterone administration generated larger and longer-lasting bubbles in that setting.</p>
<div class="research-lens callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Research Lens: what laboratory markets can transport
</div>
</div>
<div class="callout-body-container callout-body">
<p>These experiments establish that known dividend distributions, an announced horizon, larger groups, or prior experience do not invariably prevent mispricing. They also let researchers test how liquidity, financing, information, and trading rules alter the outcome. Transporting the findings requires comparing those conditions with the field market of interest.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> A historical price chart establishes a trajectory; a controlled treatment comparison can establish the effect of a particular intervention.</p>
</div>
</div>
</section>
</section>
<section id="a-two-direction-bubble-dashboard" class="level2">
<h2 data-anchor-id="a-two-direction-bubble-dashboard">Evaluating competing explanations for a boom</h2>
<p>A rising price can reflect improving prospects, a reinforcing trading process, or both. Treating every rise as confirmation of a bubble would make the diagnosis impossible to correct; dismissing every concern as innovation could leave growing exposure unchecked. Use both evidence columns in <a href="#tbl-bubble-dashboard" class="quarto-xref">Table&nbsp;<span>27.5</span></a> to record what makes the price look fragile, what could justify it, and which observation would change your assessment. A probability can help when the event and horizon are well defined.</p>
<div id="tbl-bubble-dashboard" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bubble-dashboard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;27.5: A two-direction bubble diagnostic
</figcaption>
<div aria-describedby="tbl-bubble-dashboard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Domain</th>
<th>Evidence that raises concern</th>
<th>Evidence that lowers concern</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fundamentals</td>
<td>Price requires extreme growth or implausibly low discount rates</td>
<td>Verifiable cash flows, productivity, scarcity, or lower required returns support the move</td>
</tr>
<tr class="even">
<td>Expectations and trading</td>
<td>Forecasts extrapolate gains; turnover, attention, entry, and resale talk surge</td>
<td>Expectations remain dispersed and cash-flow theses remain testable</td>
</tr>
<tr class="odd">
<td>Leverage and liquidity</td>
<td>Credit, collateral loops, maturity mismatch, or one-sided liquidity expand</td>
<td>Financing is conservative, losses absorbable, and supply responsive</td>
</tr>
<tr class="even">
<td>Arbitrage constraints</td>
<td>Shorting is costly; skeptical capital is horizon-constrained</td>
<td>Close substitutes and durable corrective capital exist</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Write both the fundamental story that would justify the price and the feedback story that would make it fragile. For each, name a discriminating observation. Even a high bubble probability does not reveal timing. Robust responses—limiting leverage and position size, stress-testing funding, preserving liquidity, and precommitting review conditions—may dominate a confident directional bet.</p>
<div class="evidence-and-boundary-conditions callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Bubble, crash, and systemic crisis are different claims
</div>
</div>
<div class="callout-body-container callout-body">
<p>A crash can occur without a prior bubble when fundamentals or discount rates change sharply. A price correction becomes a <strong>systemic crisis</strong> only when leverage, maturity mismatch, balance-sheet exposure, networks, or confidence propagate losses widely enough to impair financial intermediation or real economic activity (Brunnermeier &amp; Oehmke, 2013).</p>
<p>Policy should therefore target the mechanism rather than the label: disclosure targets information problems; underwriting standards, capital buffers, and leverage limits target fragility and loss propagation; consumer protection targets burden and informed choice. Each intervention carries false-positive costs from constraining a sustainable market and false-negative costs from leaving a dangerous mechanism unaddressed. Ask who receives the upside, who can exit, who carries the downside, and whether losses are absorbable or propagated through obligations to others.</p>
</div>
</div>
</section>
<section id="investing-when-neither-prices-nor-forecasts-are-infallible" class="level2">
<h2 data-anchor-id="investing-when-neither-prices-nor-forecasts-are-infallible">Investing when neither prices nor forecasts are infallible</h2>
<p>Return to the earnings announcement. A vivid company story can attract <a href="../chapters/09-what-feels-likely-availability-affect-and-resemblance.html#chapter-09-start">attention</a>, while a subsequent price rise appears to confirm that other investors share your information. If those investors are responding to the same announcement or copying the price, their behavior supplies less <a href="../chapters/26-social-norms-and-conformity-when-other-people-become-evidence.html#chapter-26-start">independent evidence</a> than it seems.</p>
<p>After buying, the problem changes. You may search for reasons to defend the position, treat its purchase price as the point to recover, or evaluate every fluctuation in isolation. The chapters on <a href="../chapters/10-beliefs-that-defend-themselves.html#chapter-10-start">defended beliefs</a>, <a href="../chapters/20-mental-accounting-money-is-fungible-minds-label-it.html#chapter-20-start">mental accounts</a>, and <a href="../chapters/17-prospect-theory-gains-and-losses-begin-at-a-reference-point.html#chapter-17-start">reference points</a> explain these possibilities. In a market, their consequences also depend on other traders, the size of the position, and the cost of changing it.</p>
<p>Barber and Odean (2000) found that, from February 1991 through January 1997, the most active fifth of brokerage households earned an annualized net return of 11.4%, compared with 18.5% for the least active fifth. The result is consistent with overconfidence plus trading costs.</p>
<p><strong>Technical analysis</strong> uses past prices and trading volume to identify patterns; <strong>fundamental analysis</strong> evaluates the cash flows, risks, and valuation assumptions behind a security. Both can be disciplined or impressionistic. The lecture’s comparison of real and simulated price charts warns that a persuasive-looking trend can arise without predictive content. A moving-average strategy may avoid some large declines yet lose through repeated switches in a trendless market. Compare a prespecified rule with a feasible holding strategy, using the same dates, risk exposures, and costs; a smoother return distribution alone does not establish superior performance (Malkiel, 2015).</p>
<p>A broad, low-cost index fund provides a useful comparison for an active strategy because it reduces the need to identify tomorrow’s winners. Sharpe’s (1991) arithmetic clarifies the cost hurdle: collectively, active investors hold the portion of the market not held passively. Before costs, their dollar-weighted average return must match that market; higher aggregate costs then lower their average net return. This accounting argument does not require every price to be correct and does not promise that every index fund will outperform every active manager.</p>
<p>Diversification can reduce exposure to individual firms, while compounding makes both costs and losses consequential. A positive arithmetic average does not ensure a favorable outcome when the entire portfolio is repeatedly exposed to large losses.</p>
<div class="research-lens callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Worked example: average returns and compounded wealth
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Suppose, in a deliberately hypothetical example, an investor reinvests all wealth in one independent weekly gamble that gains 80% or loses 60%, with equal probabilities. The arithmetic mean return is +10%, but one gain and one loss leave only 72% of the starting wealth. Over 52 weeks, exactly 26 gains and 26 losses—the most likely number of gains—turn €10,000 into about €1.95. The expected terminal wealth exceeds €1.4 million because rare winning paths pull up the average. The example illustrates why average returns, typical compounded outcomes, and diversification differ; it is not evidence about actual IPO performance or a proof that an index eliminates market risk.</p>
</div>
</div>
</div>
<p>A long horizon gives returns time to compound; it does not make losses impossible or a poor valuation harmless. Compare total returns, including reinvested dividends, over the same dates, and distinguish nominal from inflation-adjusted outcomes. Evidence that stocks outperformed bonds over many historical long horizons remains evidence about those samples, not a guarantee for every future investor (Siegel, 2014).</p>
<p>Preserve the pre-purchase record to apply the <a href="../chapters/01-how-decisions-should-be-made-and-how-they-actually-are.html#outcome-is-not-process">process–outcome distinction</a>. A later gain should test the recorded thesis rather than erase weaknesses in the reasoning that produced it.</p>
<p><span id="a-falsifiable-investment-memo"></span></p>
<p>An investment story can adapt easily to the next price move: a rise appears to vindicate it, while a fall becomes an opportunity to buy more. Then no outcome teaches the investor when the reasoning has failed. Before buying, turn the story into a record that specifies what must happen, what would count against it, and what action follows. Write one page:</p>
<ol type="1">
<li><strong>Decision and noninvestment option.</strong> What exactly will be done, in what size, and why is doing nothing inferior?</li>
<li><strong>Thesis.</strong> State the causal claim in one sentence.</li>
<li><strong>Embedded expectations.</strong> What does the current price already require the firm or market to achieve?</li>
<li><strong>Base rate and comparison class.</strong> What happened in similar situations?</li>
<li><strong>Drivers.</strong> Name the two or three variables that must move.</li>
<li><strong>Disconfirmation.</strong> What observation would make the thesis materially less plausible?</li>
<li><strong>Risks and dependence.</strong> Which exposures could fail together?</li>
<li><strong>Implementation.</strong> Include spreads, liquidity, taxes, financing, capacity, and time horizon.</li>
<li><strong>Position and exit rules.</strong> Precommit a maximum exposure, review date, and conditions for reducing, adding, or closing.</li>
<li><strong>Evaluation.</strong> Separate frequent risk monitoring from the horizon on which performance will be judged.</li>
</ol>
<p>Then red-team the memo. Look for an unfalsifiable escape (“the market will recognize it eventually”), a sunk argument (“we have already lost too much to sell”), a missing denominator, a selected backtest, or a position too large for the uncertainty.</p>
</section>
<section id="practice-lab" class="level2">
<h2 data-anchor-id="practice-lab">Practice Lab</h2>
<p><strong>Bubble investigation.</strong> Choose one historical episode from <a href="#tbl-historical-bubbles" class="quarto-xref">Table&nbsp;<span>27.2</span></a>. Write its fundamental-value story and its feedback story separately. Identify the financing arrangement, the evidence available before the reversal, and one observation that would distinguish the two stories. Compare it with one laboratory intervention from <a href="#tbl-bubble-experimental-conditions" class="quarto-xref">Table&nbsp;<span>27.3</span></a> and explain which institutional difference limits that comparison.</p>
<p><strong>Classroom-market debrief.</strong> If class trading data are available, first reconstruct the dividend distribution, number of periods, redemption rule, interest rate, and borrowing or short-sale constraints. Then calculate the correct benchmark for that session and compare it with actual transactions and recorded forecasts. A six-period exercise has a different horizon from the classic 15-period market. Describe the observed path without assuming in advance that a bubble or a crash occurred.</p>
<p><strong>News-timing comparison.</strong> Compare the Fed announcement with election night. Identify when the underlying information arrived, when a reader could have acted, and what the sampling frequency lets you infer. Explain why a headline can be favorable yet offer no obvious gain at the available price.</p>
<p><strong>Event-study audit.</strong> Choose a published event study discussed in this chapter or a course-provided case containing the event time, benchmark, reported abnormal return, uncertainty, and potential confounds. Produce a one-page audit that records: first public time, expected-return model, estimation and event windows, main estimate with uncertainty, overlapping news, tradable timing, and costs. End with two sentences: the strongest warranted conclusion and one stronger claim the evidence does not support.</p>
<p><strong>Advanced extension:</strong> reproduce the estimate only when the dataset, data definitions, and analysis code or a specified software template are provided. Compare your result with the published estimate and document every discrepancy before interpreting it.</p>
</section>
<section id="take-it-forward" class="level2">
<h2 data-anchor-id="take-it-forward">Take it forward</h2>
<p>The earnings announcement now poses a sharper question: what would have to be missing from the current price for buying at your available execution price to make sense? If the evidence does not answer it, a favorable headline alone cannot complete the argument. Keep the original record; later returns can then test a prediction instead of supplying a convenient explanation.</p>
<p>Prices can coordinate dispersed action without a single commander. Organizations also coordinate through leaders, roles, meetings, and assigned responsibilities. <a href="../chapters/28-authority-groupthink-and-shared-responsibility.html#authority-groupthink-and-shared-responsibility">Authority, Groupthink, and Shared Responsibility</a> asks when these concentrated social signals improve coordination and when they suppress evidence, dissent, ownership, or action.</p>
</section>
<section id="optional-research-notes" class="level2">
<h2 data-anchor-id="optional-research-notes">Optional research notes</h2>
<div id="advanced-research-track-auditing-an-event-study" class="research-lens callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Advanced research track: auditing an event study
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>An <strong>event study</strong> estimates security returns around a defined event (MacKinlay, 1997). Audit its inferential chain in this order:</p>
<ol type="1">
<li>Define the event and its first public time.</li>
<li>Specify an estimation window for the expected-return model.</li>
<li>Specify an event window in which reaction is measured.</li>
<li>Compute abnormal return as actual return minus expected return.</li>
<li>Aggregate across securities or time into average abnormal returns or cumulative abnormal returns.</li>
<li>Test uncertainty and inspect confounding events.</li>
</ol>
<p>For an audit, record the published answer to each step and mark missing information rather than inventing a price, return, or model. A full reproduction additionally requires the original sample-construction rules, data vintage, corporate-action handling, code, and trading assumptions.</p>
<p>If prices incorporate a clean public surprise rapidly, abnormal returns should cluster near the release. The continued separation after the announcement in <a href="#fig-finance-event-study-drift" class="quarto-xref">Figure&nbsp;<span>27.9</span></a> can illustrate slow updating, but an observed pattern like this could also reflect a weak benchmark, overlapping news, trading frictions, or sample construction that would not have been available in real time.</p>
<div id="fig-finance-event-study-drift" class="quarto-float quarto-figure quarto-figure-center" alt="A two-part event-study schematic. A timeline marks an estimation window, the first public event time, and a post-event window. Below, the positive- and negative-surprise paths overlap before the announcement, diverge at the announcement, and continue upward or downward afterward. A side audit lists event time, expected-return model, confounds, uncertainty, tradable timing, and costs.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-finance-event-study-drift-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/finance-event-study-drift.svg" class="img-fluid figure-img" style="width:100.0%" alt="A two-part event-study schematic. A timeline marks an estimation window, the first public event time, and a post-event window. Below, the positive- and negative-surprise paths overlap before the announcement, diverge at the announcement, and continue upward or downward afterward. A side audit lists event time, expected-return model, confounds, uncertainty, tradable timing, and costs.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-finance-event-study-drift-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.9: An event-study schematic distinguishes the estimation window, the event’s first public time, and the post-event window. In the cumulative-abnormal-return panel, positive- and negative-surprise paths share one pre-announcement baseline, diverge at the announcement, and then continue drifting apart. The curves explain the logic of post-earnings-announcement drift.
</figcaption>
</figure>
</div>
<p>Historical research on earnings announcements documented <strong>post-earnings-announcement drift</strong>: firms with high unexpected earnings continued, on average, to outperform firms with low unexpected earnings after the immediate announcement response in the studied samples (Rendleman et al., 1982). The pattern challenges the joint model used in the study.</p>
</div>
</div>
</div>
<p><span id="research-lens-five-patterns-five-open-diagnoses"></span></p>
<p><span id="research-lens-five-patterns-five-open-diagnoses-title"></span></p>
</section>
<section id="references-cited-in-this-chapter" class="level2">
<h2 data-anchor-id="references-cited-in-this-chapter">References cited in this chapter</h2>
<div class="reference">
<p>Abreu, D., &amp; Brunnermeier, M. K. (2003). Bubbles and crashes. Econometrica, 71(1), 173–204.</p>
</div>
<div class="reference">
<p>Ackert, L. F., Charupat, N., Church, B. K., &amp; Deaves, R. (2006). Margin, short selling, and lotteries in experimental asset markets. <em>Southern Economic Journal, 73</em>(2), 419–436. https://doi.org/10.1002/j.2325-8012.2006.tb00779.x</p>
</div>
<div class="reference">
<p>Associated Press. (2024, November 6). Calling the 2024 presidential race state by state. https://www.ap.org/the-definitive-source/behind-the-news/calling-the-2024-presidential-race-state-by-state/</p>
</div>
<div class="reference">
<p>Banz, R. W. (1981). The relationship between return and market value of common stocks. Journal of Financial Economics, 9(1), 3–18.</p>
</div>
<div class="reference">
<p>Barber, B. M., &amp; Odean, T. (2000). Trading is hazardous to your wealth: The common stock investment performance of individual investors. Journal of Finance, 55(2), 773–806.</p>
</div>
<div class="reference">
<p>Barberis, N., &amp; Thaler, R. (2003). A survey of behavioral finance. In G. M. Constantinides, M. Harris, &amp; R. Stulz (Eds.), Handbook of the economics of finance (Vol. 1B, pp.&nbsp;1053–1128). Elsevier.</p>
</div>
<div class="reference">
<p>Bernhardt, D., &amp; Eckblad, M. (2013). Stock market crash of 1987. <em>Federal Reserve History</em>. https://www.federalreservehistory.org/essays/stock-market-crash-of-1987</p>
</div>
<div class="reference">
<p>Bostian, A. J. A., &amp; Holt, C. A. (2009). Price bubbles with discounting: A web-based classroom experiment. <em>Journal of Economic Education, 40</em>(1), 27–37. https://doi.org/10.3200/JECE.40.1.027-037</p>
</div>
<div class="reference">
<p>Brunnermeier, M. K., &amp; Oehmke, M. (2013). Bubbles, financial crises, and systemic risk. In G. M. Constantinides, M. Harris, &amp; R. Stulz (Eds.), Handbook of the economics of finance (Vol. 2B, pp.&nbsp;1221–1288). Elsevier.</p>
</div>
<div class="reference">
<p>Caginalp, G., Porter, D. P., &amp; Smith, V. L. (1998). Initial cash/asset ratio and asset prices: An experimental study. Proceedings of the National Academy of Sciences, 95(2), 756–761.</p>
</div>
<div class="reference">
<p>Coppock, L. A., Harper, D. Q., &amp; Holt, C. A. (2021). Capital constraints and asset bubbles: An experimental study. <em>Journal of Economic Behavior &amp; Organization, 183</em>, 75–88. https://doi.org/10.1016/j.jebo.2020.10.024</p>
</div>
<div class="reference">
<p>Corgnet, B., Hernán-González, R., Kujal, P., &amp; Porter, D. (2015). The effect of earned versus house money on price bubble formation in experimental asset markets. <em>Review of Finance, 19</em>(4), 1455–1488. https://doi.org/10.1093/rof/rfu031</p>
</div>
<div class="reference">
<p>De Bondt, W. F. M., &amp; Thaler, R. (1985). Does the stock market overreact? Journal of Finance, 40(3), 793–805.</p>
</div>
<div class="reference">
<p>Deck, C., Porter, D., &amp; Smith, V. L. (2014). Double bubbles in assets markets with multiple generations. <em>Journal of Behavioral Finance, 15</em>(2), 79–88. https://doi.org/10.1080/15427560.2014.908884</p>
</div>
<div class="reference">
<p>Dufwenberg, M., Lindqvist, T., &amp; Moore, E. (2005). Bubbles and experience: An experiment. American Economic Review, 95(5), 1731–1737.</p>
</div>
<div class="reference">
<p>Eckel, C. C., &amp; Füllbrunn, S. C. (2015). Thar SHE blows? Gender, competition, and bubbles in experimental asset markets. <em>American Economic Review, 105</em>(2), 906–920. https://doi.org/10.1257/aer.20130683</p>
</div>
<div class="reference">
<p>Eckel, C. C., &amp; Füllbrunn, S. C. (2017). Hidden vs.&nbsp;known gender effects in experimental asset markets. <em>Economics Letters, 156</em>, 7–9.</p>
</div>
<div class="reference">
<p>Fama, E. F. (1970). Efficient capital markets: A review of theory and empirical work. Journal of Finance, 25(2), 383–417.</p>
</div>
<div class="reference">
<p>Fama, E. F. (1991). Efficient capital markets: II. Journal of Finance, 46(5), 1575–1617.</p>
</div>
<div class="reference">
<p>Fama, E. F., &amp; French, K. R. (1992). The cross-section of expected stock returns. Journal of Finance, 47(2), 427–465.</p>
</div>
<div class="reference">
<p>Fama, E. F., &amp; French, K. R. (1993). Common risk factors in the returns on stocks and bonds. <em>Journal of Financial Economics, 33</em>(1), 3–56. https://doi.org/10.1016/0304-405X(93)90023-5</p>
</div>
<div class="reference">
<p>Fama, E. F., &amp; French, K. R. (1998). Value versus growth: The international evidence. Journal of Finance, 53(6), 1975–1999.</p>
</div>
<div class="reference">
<p>Federal Open Market Committee. (2013, September 18). FOMC statement. <em>Board of Governors of the Federal Reserve System</em>. https://www.federalreserve.gov/newsevents/pressreleases/monetary20130918a.htm</p>
</div>
<div class="reference">
<p>Federal Reserve Bank of St.&nbsp;Louis. (2026). NASDAQ Composite [NASDAQCOM]. <em>FRED</em>. Retrieved August 29, 2026, from https://fred.stlouisfed.org/series/NASDAQCOM</p>
</div>
<div class="reference">
<p>Goldgar, A. (2007). <em>Tulipmania: Money, honor, and knowledge in the Dutch Golden Age</em>. University of Chicago Press. https://press.uchicago.edu/ucp/books/book/chicago/T/bo5414939.html</p>
</div>
<div class="reference">
<p>Greenwood, R., &amp; Shleifer, A. (2014). Expectations of returns and expected returns. Review of Financial Studies, 27(3), 714–746.</p>
</div>
<div class="reference">
<p>Grossman, S. J., &amp; Stiglitz, J. E. (1980). On the impossibility of informationally efficient markets. American Economic Review, 70(3), 393–408.</p>
</div>
<div class="reference">
<p>Haruvy, E., Lahav, Y., &amp; Noussair, C. N. (2007). Traders’ expectations in asset markets: Experimental evidence. American Economic Review, 97(5), 1901–1920.</p>
</div>
<div class="reference">
<p>Haruvy, E., &amp; Noussair, C. N. (2006). The effect of short selling on bubbles and crashes in experimental spot asset markets. Journal of Finance, 61(3), 1119–1157.</p>
</div>
<div class="reference">
<p>Harvey, C. R., Liu, Y., &amp; Zhu, H. (2016). … and the cross-section of expected returns. Review of Financial Studies, 29(1), 5–68.</p>
</div>
<div class="reference">
<p>Holt, C. A., Porzio, M., &amp; Song, M. Y. (2017). Price bubbles, gender, and expectations in experimental asset markets. European Economic Review, 100, 72–94.</p>
</div>
<div class="reference">
<p>Hussam, R. N., Porter, D., &amp; Smith, V. L. (2008). Thar she blows: Can bubbles be rekindled with experienced subjects? American Economic Review, 98(3), 924–937.</p>
</div>
<div class="reference">
<p>Jegadeesh, N., &amp; Titman, S. (1993). Returns to buying winners and selling losers: Implications for stock market efficiency. Journal of Finance, 48(1), 65–91.</p>
</div>
<div class="reference">
<p>Kalshi. (n.d.). Historical candlesticks for PRES-2024-DJT, October–November 2024 [Data set]. https://docs.kalshi.com/api-reference/historical/get-historical-market-candlesticks</p>
</div>
<div class="reference">
<p>Kindleberger, C. P., &amp; Aliber, R. Z. (2011). <em>Manias, panics, and crashes: A history of financial crises</em> (6th ed.). Palgrave Macmillan.</p>
</div>
<div class="reference">
<p>Lamont, O. A., &amp; Thaler, R. H. (2003). Can the market add and subtract? Mispricing in tech stock carve-outs. Journal of Political Economy, 111(2), 227–268.</p>
</div>
<div class="reference">
<p>Lei, V., Noussair, C. N., &amp; Plott, C. R. (2001). Nonspeculative bubbles in experimental asset markets: Lack of common knowledge of rationality vs.&nbsp;actual irrationality. <em>Econometrica, 69</em>(4), 831–859. https://doi.org/10.1111/1468-0262.00222</p>
</div>
<div class="reference">
<p>MacKinlay, A. C. (1997). Event studies in economics and finance. Journal of Economic Literature, 35(1), 13–39.</p>
</div>
<div class="reference">
<p>Malkiel, B. G. (2015). <em>A random walk down Wall Street: The time-tested strategy for successful investing</em> (11th ed.). W. W. Norton.</p>
</div>
<div class="reference">
<p>Maloney, M. T., &amp; Mulherin, J. H. (2003). The complexity of price discovery in an efficient market: The stock market reaction to the Challenger crash. Journal of Corporate Finance, 9(4), 453–479.</p>
</div>
<div class="reference">
<p>McKinsey Global Institute. (2013, November). <em>QE and ultra-low interest rates: Distributional effects and risks</em>. https://www.mckinsey.com/featured-insights/employment-and-growth/qe-and-ultra-low-interest-rates-distributional-effects-and-risks</p>
</div>
<div class="reference">
<p>McLean, R. D., &amp; Pontiff, J. (2016). Does academic research destroy stock return predictability? Journal of Finance, 71(1), 5–32.</p>
</div>
<div class="reference">
<p>Nadler, A., Jiao, P., Johnson, C. J., Alexander, V., &amp; Zak, P. J. (2018). The bull of Wall Street: Experimental analysis of testosterone and asset trading. <em>Management Science, 64</em>(9), 4032–4051. https://doi.org/10.1287/mnsc.2017.2836</p>
</div>
<div class="reference">
<p>Odlyzko, A. (2020). Isaac Newton and the perils of the financial South Sea. <em>Physics Today, 73</em>(7), 30–36. https://doi.org/10.1063/PT.3.4521</p>
</div>
<div class="reference">
<p>Ofek, E., &amp; Richardson, M. (2003). DotCom mania: The rise and fall of internet stock prices. Journal of Finance, 58(3), 1113–1137.</p>
</div>
<div class="reference">
<p>Porter, D. P., &amp; Smith, V. L. (2003). Stock market bubbles in the laboratory. Journal of Behavioral Finance, 4(1), 7–20.</p>
</div>
<div class="reference">
<p>Rendleman, R. J., Jr., Jones, C. P., &amp; Latané, H. A. (1982). Empirical anomalies based on unexpected earnings and the importance of risk adjustments. Journal of Financial Economics, 10(3), 269–287.</p>
</div>
<div class="reference">
<p>Rich, R. (2013). The Great Recession. <em>Federal Reserve History</em>. https://www.federalreservehistory.org/essays/great-recession-of-200709</p>
</div>
<div class="reference">
<p>Richardson, G., Komai, A., Gou, M., &amp; Park, D. (2013). Stock market crash of 1929. <em>Federal Reserve History</em>. https://www.federalreservehistory.org/essays/stock-market-crash-of-1929</p>
</div>
<div class="reference">
<p>Rodrigue, J.-P. (n.d.). Stages in a bubble. <em>The Geography of Transport Systems</em>. https://transportgeography.org/contents/chapter3/transportation-and-economic-development/bubble-stages/</p>
</div>
<div class="reference">
<p>Scheinkman, J. A., &amp; Xiong, W. (2003). Overconfidence and speculative bubbles. <em>Journal of Political Economy, 111</em>(6), 1183–1220.</p>
</div>
<div class="reference">
<p>Sharpe, W. F. (1964). Capital asset prices: A theory of market equilibrium under conditions of risk. <em>Journal of Finance, 19</em>(3), 425–442. https://doi.org/10.1111/j.1540-6261.1964.tb02865.x</p>
</div>
<div class="reference">
<p>Sharpe, W. F. (1991). The arithmetic of active management. <em>Financial Analysts Journal, 47</em>(1), 7–9. https://web.stanford.edu/~wfsharpe/art/active/active.htm</p>
</div>
<div class="reference">
<p>Shiller, R. J. (1981). Do stock prices move too much to be justified by subsequent changes in dividends? <em>American Economic Review, 71</em>(3), 421–436.</p>
</div>
<div class="reference">
<p>Shiller, R. J. (2000). Irrational exuberance. Princeton University Press.</p>
</div>
<div class="reference">
<p>Shiller, R. J. (2013). Yes, we’re confident, but who knows why. <em>Yale Insights</em>. https://insights.som.yale.edu/insights/yes-we-re-confident-but-who-knows-why</p>
</div>
<div class="reference">
<p>Shleifer, A., &amp; Vishny, R. W. (1997). The limits of arbitrage. Journal of Finance, 52(1), 35–55.</p>
</div>
<div class="reference">
<p>Siegel, J. J. (2008). <em>Stocks for the long run: The definitive guide to financial market returns and long-term investment strategies</em> (4th ed.). McGraw-Hill.</p>
</div>
<div class="reference">
<p>Siegel, J. J. (2014). <em>Stocks for the long run: The definitive guide to financial market returns and long-term investment strategies</em> (5th ed.). McGraw-Hill.</p>
</div>
<div class="reference">
<p>Sims, J., &amp; Romero, J. (2013). Latin American debt crisis of the 1980s. <em>Federal Reserve History</em>. https://www.federalreservehistory.org/essays/latin-american-debt-crisis</p>
</div>
<div class="reference">
<p>Smith, V. L., Suchanek, G. L., &amp; Williams, A. W. (1988). Bubbles, crashes, and endogenous expectations in experimental spot asset markets. Econometrica, 56(5), 1119–1151.</p>
</div>
<div class="reference">
<p>Smith, V. L., van Boening, M., &amp; Wellford, C. P. (2000). Dividend timing and behavior in laboratory asset markets. <em>Economic Theory, 16</em>(3), 567–583. https://doi.org/10.1007/PL00020943</p>
</div>
<div class="reference">
<p>Thaler, R. H. (2016). Behavioral economics: Past, present, and future. <em>American Economic Review, 106</em>(7), 1577–1600. https://doi.org/10.1257/aer.106.7.1577</p>
</div>
<div class="reference">
<p>Tucker, S., &amp; Xu, Y. (2024). Nonspeculative bubbles revisited. <em>Journal of Behavioral and Experimental Finance, 42</em>, 100925. https://doi.org/10.1016/j.jbef.2024.100925</p>
</div>
<div class="reference">
<p>Velde, F. R. (2003). <em>Government equity and money: John Law’s system in 1720 France</em> (Working Paper No.&nbsp;2003-31). Federal Reserve Bank of Chicago. https://www.chicagofed.org/publications/working-papers/2003/2003-31</p>
</div>
<div class="reference">
<p>Wang, J., Houser, D., &amp; Xu, H. (2018). Culture, gender and asset prices: Experimental evidence from the U.S. and China. <em>Journal of Economic Behavior &amp; Organization, 155</em>, 253–287. https://doi.org/10.1016/j.jebo.2018.09.003</p>
</div>
<div class="reference">
<p>Weinberg, J. (2013). The Great Recession and its aftermath. <em>Federal Reserve History</em>. https://www.federalreservehistory.org/essays/great-recession-and-its-aftermath</p>
</div>
<div class="reference">
<p>Williams, A. W. (2008). Price bubbles in large financial asset markets. In C. R. Plott &amp; V. L. Smith (Eds.), <em>Handbook of experimental economics results</em> (Vol. 1, pp.&nbsp;242–246). North-Holland. https://doi.org/10.1016/S1574-0722(07)00029-7</p>
</div>
<div class="reference">
<p>Yahoo Finance. (n.d.). E-mini S&amp;P 500 futures (ES=F): Hourly observations for November 2024 [Data set]. https://finance.yahoo.com/quote/ES%3DF/history/</p>
</div>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Applying a laboratory estimate to a field market requires comparing participants, stakes, institutions, leverage, information, and asset supply.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark_dimmed">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "warrenchang/decisionbook";
    script.dataset.repoId = "R_kgDOTpqPRg";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOTpqPRs4DCa1q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/26-social-norms-and-conformity-when-other-people-become-evidence.html" class="pagination-link" aria-label="Social Norms and Conformity">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Social Norms and Conformity</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/28-authority-groupthink-and-shared-responsibility.html" class="pagination-link" aria-label="Authority, Groupthink, and Shared Responsibility">
        <span class="nav-page-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Authority, Groupthink, and Shared Responsibility</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Huanren Warren Zhang. All rights reserved.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/warrenchang/decisionbook/edit/main/chapters/27-markets-mispricing-and-bubbles.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/warrenchang/decisionbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/warrenchang/decisionbook/blob/main/chapters/27-markets-mispricing-and-bubbles.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>